# **Task 2 - загрузить датасет и сделать выборки в рамках требований**

# **Признаки датасета "Титаник" с их описанием:**

**PassengerId:** Уникальный идентификатор пассажира.

**Survived:** Выжил ли пассажир (1 - да, 0 - нет).

**Pclass:** Класс пассажира (1 - Первый класс, 2 - Второй класс, 3 - Третий класс).

**Name:** Имя пассажира.

**Sex:** Пол пассажира (male - мужской, female - женский).

**Age:** Возраст пассажира.

**SibSp:** Количество братьев/сестер/супругов на борту.

**Parch:** Количество родителей/детей на борту.

**Ticket:** Номер билета.

**Fare:** Стоимость билета.

**Cabin:** Номер каюты.

**Embarked:** Порт отправления (C - Cherbourg, Q - Queenstown, S - Southampton).

**Задание 1**

In [ ]:
# здесь импортируйте пандас и датасет

**Задание №2**

1) Выберите всех пассажиров первого класса: Найдите всех пассажиров, которые ехали в первом классе.

2) Найдите всех выживших пассажиров: Отберите строки, где пассажиры выжили .

3) Фильтрация по возрасту: Выберите всех пассажиров младше 18 лет.

4) Отбор по порту отправления: Найдите всех пассажиров, которые сели на корабль в Саутгемптоне.

5) Поиск по фамилии: Найдите всех пассажиров с фамилией, начинающейся на "Smith".

6) Отбор по стоимости билета: Отберите всех пассажиров, стоимость билета которых была больше 50.

7) Фильтрация по полу: Найдите всех пассажиров женского пола.

8) Отбор пассажиров с несколькими членами семьи на борту: Выберите всех пассажиров, у которых было больше 2 членов семьи на борту.

9) Поиск пассажиров с номером каюты: Найдите всех пассажиров, у которых указан номер каюты (Cabin не пустое значение).

In [ ]:
# ваш код здесь

**Задание № 3**

1) Выберите всех выживших пассажиров первого класса: Найдите всех пассажиров, которые ехали в первом классе и выжили.

2) Найдите всех несовершеннолетних, путешествовавших с родителями: Выберите пассажиров младше 18 лет, у которых было хотя бы одно количество родителей на борту.

3) Пассажиры с дорогими билетами и большим возрастом: Найдите всех пассажиров, возраст которых больше 50 лет и стоимость билета которых превышает 100.

4) Женщины, которые выжили и ехали из Квинстауна: Выберите женщин, которые выжили и сели на корабль в Квинстауне.

5) Мужчины третьего класса, путешествовавшие с братьями и сестрами: Найдите всех мужчин, которые ехали в третьем классе и имели хотя бы одного брата или сестру на борту.

6) Пассажиры второго класса с отсутствующим возрастом: Найдите всех пассажиров второго класса, у которых возраст не указан (Age is null).

7) Мужчины старше 30 лет, которые выжили: Выберите всех мужчин старше 30 лет, которые выжили.

8) Дети, ехавшие с обоими родителями: Найдите всех детей младше 12 лет, у которых было как минимум два родителя на борту.

9) Пассажиры старше 60 лет, ехавшие в первом классе, которые не выжили: Выберите всех пассажиров старше 60 лет, которые ехали в первом классе и не выжили.

In [ ]:
# ваш код здесь