# **Task 2 - загрузить датасет и сделать выборки в рамках требований**

# **Признаки датасета "Титаник" с их описанием:**

**PassengerId:** Уникальный идентификатор пассажира.

**Survived:** Выжил ли пассажир (1 - да, 0 - нет).

**Pclass:** Класс пассажира (1 - Первый класс, 2 - Второй класс, 3 - Третий класс).

**Name:** Имя пассажира.

**Sex:** Пол пассажира (male - мужской, female - женский).

**Age:** Возраст пассажира.

**SibSp:** Количество братьев/сестер/супругов на борту.

**Parch:** Количество родителей/детей на борту.

**Ticket:** Номер билета.

**Fare:** Стоимость билета.

**Cabin:** Номер каюты.

**Embarked:** Порт отправления (C - Cherbourg, Q - Queenstown, S - Southampton).

**Задание 1**

In [3]:
setwd('/Users/andreypovaliy/Documents/Education/ITMO_DS/05_python_for_data_analysis/')

titanic = read.csv('./lect/data/titanic.csv')
titanic

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
... ...         ...      ...
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
... ...                                                       ...    ... ...
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked
1   0     A/5 21171          7.2500             S
2   0     PC 17599          71.2833 C85         C
3   0     STON/O2. 3101282   7.9250             S
4   0     113803            53.1000 C123        S
5   0     373450             8.0500             S
6   0     330877             8.4583             Q
7   0     17463             51.8625 E46         S
8   1     349909            21.0750             S
9   2     347742            11.1333             S
10  0     237736            30.0708             C
11  1     PP 9549           16.7000 G6          S
12  0     113783            26.5500 C103        S
13  0     A/5. 2151          8.0500             S
14  5     347082            31.2750             S
15  0     350406             7.8542             S
16  0     248706            16.0000             S
17  1     382652            29.1250             Q
18  0     244373            13.0000             S
19  0     345763            18.0000             S
20  0     2649               7.2250             C
21  0     239865            26.0000             S
22  0     248698            13.0000 D56         S
23  0     330923             8.0292             Q
24  0     113788            35.5000 A6          S
25  1     349909            21.0750             S
26  5     347077            31.3875             S
27  0     2631               7.2250             C
28  2     19950            263.0000 C23 C25 C27 S
29  0     330959             7.8792             Q
30  0     349216             7.8958             S
... ...   ...              ...      ...         ...
862 0     28134            11.5000              S
863 0     17466            25.9292  D17         S
864 2     CA. 2343         69.5500              S
865 0     233866           13.0000              S
866 0     236852           13.0000              S
867 0     SC/PARIS 2149    13.8583              C
868 0     PC 17590         50.4958  A24         S
869 0     345777            9.5000              S
870 1     347742           11.1333              S
871 0     349248            7.8958              S
872 1     11751            52.5542  D35         S
873 0     695               5.0000  B51 B53 B55 S
874 0     345765            9.0000              S
875 0     P/PP 3381        24.0000              C
876 0     2667              7.2250              C
877 0     7534              9.8458              S
878 0     349212            7.8958              S
879 0     349217            7.8958              S
880 1     11767            83.1583  C50         C
881 1     230433           26.0000              S
882 0     349257            7.8958              S
883 0     7552             10.5167              S
884 0     C.A./SOTON 34068 10.5000              S
885 0     SOTON/OQ 392076   7.0500              S
886 5     382652           29.1250              Q
887 0     211536           13.0000              S
888 0     112053           30.0000  B42         S
889 2     W./C. 6607       23.4500              S
890 0     111369           30.0000  C148        C
891 0     370376            7.7500              Q

**Задание №2**

1) Выберите всех пассажиров первого класса: Найдите всех пассажиров, которые ехали в первом классе.

2) Найдите всех выживших пассажиров: Отберите строки, где пассажиры выжили .

3) Фильтрация по возрасту: Выберите всех пассажиров младше 18 лет.

4) Отбор по порту отправления: Найдите всех пассажиров, которые сели на корабль в Саутгемптоне.

5) Поиск по фамилии: Найдите всех пассажиров с фамилией, начинающейся на "Smith".

6) Отбор по стоимости билета: Отберите всех пассажиров, стоимость билета которых была больше 50.

7) Фильтрация по полу: Найдите всех пассажиров женского пола.

8) Отбор пассажиров с несколькими членами семьи на борту: Выберите всех пассажиров, у которых было больше 2 членов семьи на борту.

9) Поиск пассажиров с номером каюты: Найдите всех пассажиров, у которых указан номер каюты (Cabin не пустое значение).

In [4]:
# 1) Выберите всех пассажиров первого класса: Найдите всех пассажиров, которые ехали в первом классе.
subset(titanic,titanic$Pclass == 1)

    PassengerId Survived Pclass
2     2         1        1
4     4         1        1
7     7         0        1
12   12         1        1
24   24         1        1
28   28         0        1
31   31         0        1
32   32         1        1
35   35         0        1
36   36         0        1
53   53         1        1
55   55         0        1
56   56         1        1
62   62         1        1
63   63         0        1
65   65         0        1
84   84         0        1
89   89         1        1
93   93         0        1
97   97         0        1
98   98         1        1
103 103         0        1
111 111         0        1
119 119         0        1
125 125         0        1
137 137         1        1
138 138         0        1
140 140         0        1
152 152         1        1
156 156         0        1
... ...         ...      ...
764 764         1        1
766 766         1        1
767 767         0        1
780 780         1        1
782 782         1        1
783 783         0        1
790 790         0        1
794 794         0        1
797 797         1        1
803 803         1        1
807 807         0        1
810 810         1        1
816 816         0        1
821 821         1        1
823 823         0        1
830 830         1        1
836 836         1        1
840 840         1        1
843 843         1        1
850 850         1        1
854 854         1        1
857 857         1        1
858 858         1        1
863 863         1        1
868 868         0        1
872 872         1        1
873 873         0        1
880 880         1        1
888 888         1        1
890 890         1        1
    Name                                                  Sex    Age SibSp
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)   female 38  1
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)          female 35  1
7   McCarthy, Mr. Timothy J                               male   54  0
12  Bonnell, Miss. Elizabeth                              female 58  0
24  Sloper, Mr. William Thompson                          male   28  0
28  Fortune, Mr. Charles Alexander                        male   19  3
31  Uruchurtu, Don. Manuel E                              male   40  0
32  Spencer, Mrs. William Augustus (Marie Eugenie)        female NA  1
35  Meyer, Mr. Edgar Joseph                               male   28  1
36  Holverson, Mr. Alexander Oskar                        male   42  1
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)              female 49  1
55  Ostby, Mr. Engelhart Cornelius                        male   65  0
56  Woolner, Mr. Hugh                                     male   NA  0
62  Icard, Miss. Amelie                                   female 38  0
63  Harris, Mr. Henry Birkhardt                           male   45  1
65  Stewart, Mr. Albert A                                 male   NA  0
84  Carrau, Mr. Francisco M                               male   28  0
89  Fortune, Miss. Mabel Helen                            female 23  3
93  Chaffee, Mr. Herbert Fuller                           male   46  1
97  Goldschmidt, Mr. George B                             male   71  0
98  Greenfield, Mr. William Bertram                       male   23  0
103 White, Mr. Richard Frasar                             male   21  0
111 Porter, Mr. Walter Chamberlain                        male   47  0
119 Baxter, Mr. Quigg Edmond                              male   24  0
125 White, Mr. Percival Wayland                           male   54  0
137 Newsom, Miss. Helen Monypeny                          female 19  0
138 Futrelle, Mr. Jacques Heath                           male   37  1
140 Giglio, Mr. Victor                                    male   24  0
152 Pears, Mrs. Thomas (Edith Wearne)                     female 22  1
156 Williams, Mr. Charles Duane                           male   51  0
... ...                                                   ...    ... ...
764 Carter, Mrs. William Ernest (Lucile Polk)             female 36  1
766 Hogeboom, Mrs. John C (Anna Andrews)                  female 51  1
767 Brewe, Dr. Arthur Jackson                             male   NA  0
780 Robert, Mrs. Edward Scott (Elisabeth Walton McMillan) female 43  0
782 Dick, Mrs. Albert Adrian (Vera Gillespie)             female 17  1
783 Long, Mr. Milton Clyde                                male   29  0
790 Guggenheim, Mr. Benjamin                              male   46  0
794 Hoyt, Mr. William Fisher                              male   NA  0
797 Leader, Dr. Alice (Farnham)                           female 49  0
803 Carter, Master. William Thornton II                   male   11  1
807 Andrews, Mr. Thomas Jr                                male   39  0
810 Chambers, Mrs. Norman Campbell (Bertha Griggs)        female 33  1
816 Fry, Mr. Richard                                      male   NA  0
821 Hays, Mrs. Charles Melville (Clara Jennings Gregg)    female 52  1
823 Reuchlin, Jonkheer. John George                       male   38  0
830 Stone, Mrs. George Nelson (Martha Evelyn)             female 62  0
836 Compton, Miss. Sara Rebecca                           female 39  1
840 Marechal, Mr. Pierre                                  male   NA  0
843 Serepeca, Miss. Augusta                               female 30  0
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)          female NA  1
854 Lines, Miss. Mary Conover                             female 16  0
857 Wick, Mrs. George Dennick (Mary Hitchcock)            female 45  1
858 Daly, Mr. Peter Denis                                 male   51  0
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)   female 48  0
868 Roebling, Mr. Washington Augustus II                  male   31  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)      female 47  1
873 Carlsson, Mr. Frans Olof                              male   33  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)         female 56  0
888 Graham, Miss. Margaret Edith                          female 19  0
890 Behr, Mr. Karl Howell                                 male   26  0
    Parch Ticket      Fare     Cabin       Embarked
2   0     PC 17599     71.2833 C85         C
4   0     113803       53.1000 C123        S
7   0     17463        51.8625 E46         S
12  0     113783       26.5500 C103        S
24  0     113788       35.5000 A6          S
28  2     19950       263.0000 C23 C25 C27 S
31  0     PC 17601     27.7208             C
32  0     PC 17569    146.5208 B78         C
35  0     PC 17604     82.1708             C
36  0     113789       52.0000             S
53  0     PC 17572     76.7292 D33         C
55  1     113509       61.9792 B30         C
56  0     19947        35.5000 C52         S
62  0     113572       80.0000 B28
63  0     36973        83.4750 C83         S
65  0     PC 17605     27.7208             C
84  0     113059       47.1000             S
89  2     19950       263.0000 C23 C25 C27 S
93  0     W.E.P. 5734  61.1750 E31         S
97  0     PC 17754     34.6542 A5          C
98  1     PC 17759     63.3583 D10 D12     C
103 1     35281        77.2875 D26         S
111 0     110465       52.0000 C110        S
119 1     PC 17558    247.5208 B58 B60     C
125 1     35281        77.2875 D26         S
137 2     11752        26.2833 D47         S
138 0     113803       53.1000 C123        S
140 0     PC 17593     79.2000 B86         C
152 0     113776       66.6000 C2          S
156 1     PC 17597     61.3792             C
... ...   ...         ...      ...         ...
764 2     113760      120.0000 B96 B98     S
766 0     13502        77.9583 D11         S
767 0     112379       39.6000             C
780 1     24160       211.3375 B3          S
782 0     17474        57.0000 B20         S
783 0     113501       30.0000 D6          S
790 0     PC 17593     79.2000 B82 B84     C
794 0     PC 17600     30.6958             C
797 0     17465        25.9292 D17         S
803 2     113760      120.0000 B96 B98     S
807 0     112050        0.0000 A36         S
810 0     113806       53.1000 E8          S
816 0     112058        0.0000 B102        S
821 1     12749        93.5000 B69         S
823 0     19972         0.0000             S
830 0     113572       80.0000 B28
836 1     PC 17756     83.1583 E49         C
840 0     11774        29.7000 C47         C
843 0     113798       31.0000             C
850 0     17453        89.1042 C92         C
854 1     PC 17592     39.4000 D28         S
857 1     36928       164.8667             S
858 0     113055       26.5500 E17         S
863 0     17466        25.9292 D17         S
868 0     PC 17590     50.4958 A24         S
872 1     11751        52.5542 D35         S
873 0     695           5.0000 B51 B53 B55 S
880 1     11767        83.1583 C50         C
888 0     112053       30.0000 B42         S
890 0     111369       30.0000 C148        C

In [5]:
# 2) Найдите всех выживших пассажиров: Отберите строки, где пассажиры выжили .
subset(titanic,titanic$Survived == 1)

    PassengerId Survived Pclass
2    2          1        1
3    3          1        3
4    4          1        1
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
16  16          1        2
18  18          1        2
20  20          1        3
22  22          1        2
23  23          1        3
24  24          1        1
26  26          1        3
29  29          1        3
32  32          1        1
33  33          1        3
37  37          1        3
40  40          1        3
44  44          1        2
45  45          1        3
48  48          1        3
53  53          1        1
54  54          1        2
56  56          1        1
57  57          1        2
59  59          1        2
62  62          1        1
66  66          1        3
67  67          1        2
... ...         ...      ...
810 810         1        1
821 821         1        1
822 822         1        3
824 824         1        3
828 828         1        2
829 829         1        3
830 830         1        1
831 831         1        3
832 832         1        2
836 836         1        1
839 839         1        3
840 840         1        1
843 843         1        1
850 850         1        1
854 854         1        1
856 856         1        3
857 857         1        1
858 858         1        1
859 859         1        3
863 863         1        1
866 866         1        2
867 867         1        2
870 870         1        3
872 872         1        1
875 875         1        2
876 876         1        3
880 880         1        1
881 881         1        2
888 888         1        1
890 890         1        1
    Name                                                      Sex    Age
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38
3   Heikkinen, Miss. Laina                                    female 26
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14
11  Sandstrom, Miss. Marguerite Rut                           female  4
12  Bonnell, Miss. Elizabeth                                  female 58
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55
18  Williams, Mr. Charles Eugene                              male   NA
20  Masselmani, Mrs. Fatima                                   female NA
22  Beesley, Mr. Lawrence                                     male   34
23  McGowan, Miss. Anna "Annie"                               female 15
24  Sloper, Mr. William Thompson                              male   28
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA
32  Spencer, Mrs. William Augustus (Marie Eugenie)            female NA
33  Glynn, Miss. Mary Agatha                                  female NA
37  Mamee, Mr. Hanna                                          male   NA
40  Nicola-Yarred, Miss. Jamila                               female 14
44  Laroche, Miss. Simonne Marie Anne Andree                  female  3
45  Devaney, Miss. Margaret Delia                             female 19
48  O'Driscoll, Miss. Bridget                                 female NA
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)                  female 49
54  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)        female 29
56  Woolner, Mr. Hugh                                         male   NA
57  Rugg, Miss. Emily                                         female 21
59  West, Miss. Constance Mirium                              female  5
62  Icard, Miss. Amelie                                       female 38
66  Moubarek, Master. Gerios                                  male   NA
67  Nye, Mrs. (Elizabeth Ramell)                              female 29
... ...                                                       ...    ...
810 Chambers, Mrs. Norman Campbell (Bertha Griggs)            female 33.00
821 Hays, Mrs. Charles Melville (Clara Jennings Gregg)        female 52.00
822 Lulic, Mr. Nikola                                         male   27.00
824 Moor, Mrs. (Beila)                                        female 27.00
828 Mallet, Master. Andre                                     male    1.00
829 McCormack, Mr. Thomas Joseph                              male      NA
830 Stone, Mrs. George Nelson (Martha Evelyn)                 female 62.00
831 Yasbeck, Mrs. Antoni (Selini Alexander)                   female 15.00
832 Richards, Master. George Sibley                           male    0.83
836 Compton, Miss. Sara Rebecca                               female 39.00
839 Chip, Mr. Chang                                           male   32.00
840 Marechal, Mr. Pierre                                      male      NA
843 Serepeca, Miss. Augusta                                   female 30.00
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)              female    NA
854 Lines, Miss. Mary Conover                                 female 16.00
856 Aks, Mrs. Sam (Leah Rosen)                                female 18.00
857 Wick, Mrs. George Dennick (Mary Hitchcock)                female 45.00
858 Daly, Mr. Peter Denis                                     male   51.00
859 Baclini, Mrs. Solomon (Latifa Qurban)                     female 24.00
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48.00
866 Bystrom, Mrs. (Karolina)                                  female 42.00
867 Duran y More, Miss. Asuncion                              female 27.00
870 Johnson, Master. Harold Theodor                           male    4.00
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47.00
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28.00
876 Najib, Miss. Adele Kiamie "Jane"                          female 15.00
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56.00
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25.00
888 Graham, Miss. Margaret Edith                              female 19.00
890 Behr, Mr. Karl Howell                                     male   26.00
    SibSp Parch Ticket           Fare     Cabin Embarked
2   1     0     PC 17599          71.2833 C85   C
3   0     0     STON/O2. 3101282   7.9250       S
4   1     0     113803            53.1000 C123  S
9   0     2     347742            11.1333       S
10  1     0     237736            30.0708       C
11  1     1     PP 9549           16.7000 G6    S
12  0     0     113783            26.5500 C103  S
16  0     0     248706            16.0000       S
18  0     0     244373            13.0000       S
20  0     0     2649               7.2250       C
22  0     0     248698            13.0000 D56   S
23  0     0     330923             8.0292       Q
24  0     0     113788            35.5000 A6    S
26  1     5     347077            31.3875       S
29  0     0     330959             7.8792       Q
32  1     0     PC 17569         146.5208 B78   C
33  0     0     335677             7.7500       Q
37  0     0     2677               7.2292       C
40  1     0     2651              11.2417       C
44  1     2     SC/Paris 2123     41.5792       C
45  0     0     330958             7.8792       Q
48  0     0     14311              7.7500       Q
53  1     0     PC 17572          76.7292 D33   C
54  1     0     2926              26.0000       S
56  0     0     19947             35.5000 C52   S
57  0     0     C.A. 31026        10.5000       S
59  1     2     C.A. 34651        27.7500       S
62  0     0     113572            80.0000 B28
66  1     1     2661              15.2458       C
67  0     0     C.A. 29395        10.5000 F33   S
... ...   ...   ...              ...      ...   ...
810 1     0     113806            53.1000 E8    S
821 1     1     12749             93.5000 B69   S
822 0     0     315098             8.6625       S
824 0     1     392096            12.4750 E121  S
828 0     2     S.C./PARIS 2079   37.0042       C
829 0     0     367228             7.7500       Q
830 0     0     113572            80.0000 B28
831 1     0     2659              14.4542       C
832 1     1     29106             18.7500       S
836 1     1     PC 17756          83.1583 E49   C
839 0     0     1601              56.4958       S
840 0     0     11774             29.7000 C47   C
843 0     0     113798            31.0000       C
850 1     0     17453             89.1042 C92   C
854 0     1     PC 17592          39.4000 D28   S
856 0     1     392091             9.3500       S
857 1     1     36928            164.8667       S
858 0     0     113055            26.5500 E17   S
859 0     3     2666              19.2583       C
863 0     0     17466             25.9292 D17   S
866 0     0     236852            13.0000       S
867 1     0     SC/PARIS 2149     13.8583       C
870 1     1     347742            11.1333       S
872 1     1     11751             52.5542 D35   S
875 1     0     P/PP 3381         24.0000       C
876 0     0     2667               7.2250       C
880 0     1     11767             83.1583 C50   C
881 0     1     230433            26.0000       S
888 0     0     112053            30.0000 B42   S
890 0     0     111369            30.0000 C148  C

In [6]:
# 3) Фильтрация по возрасту: Выберите всех пассажиров младше 18 лет.
subset(titanic, titanic$Age < 18)

    PassengerId Survived Pclass Name
8     8         0        3      Palsson, Master. Gosta Leonard
10   10         1        2      Nasser, Mrs. Nicholas (Adele Achem)
11   11         1        3      Sandstrom, Miss. Marguerite Rut
15   15         0        3      Vestrom, Miss. Hulda Amanda Adolfina
17   17         0        3      Rice, Master. Eugene
23   23         1        3      McGowan, Miss. Anna "Annie"
25   25         0        3      Palsson, Miss. Torborg Danira
40   40         1        3      Nicola-Yarred, Miss. Jamila
44   44         1        2      Laroche, Miss. Simonne Marie Anne Andree
51   51         0        3      Panula, Master. Juha Niilo
59   59         1        2      West, Miss. Constance Mirium
60   60         0        3      Goodwin, Master. William Frederick
64   64         0        3      Skoog, Master. Harald
69   69         1        3      Andersson, Miss. Erna Alexandra
72   72         0        3      Goodwin, Miss. Lillian Amy
79   79         1        2      Caldwell, Master. Alden Gates
85   85         1        2      Ilett, Miss. Bertha
87   87         0        3      Ford, Mr. William Neal
112 112         0        3      Zabour, Miss. Hileni
115 115         0        3      Attalah, Miss. Malake
120 120         0        3      Andersson, Miss. Ellis Anna Maria
126 126         1        3      Nicola-Yarred, Master. Elias
139 139         0        3      Osen, Mr. Olaf Elon
148 148         0        3      Ford, Miss. Robina Maggie "Ruby"
157 157         1        3      Gilnagh, Miss. Katherine "Katie"
164 164         0        3      Calic, Mr. Jovo
165 165         0        3      Panula, Master. Eino Viljami
166 166         1        3      Goldsmith, Master. Frank John William "Frankie"
172 172         0        3      Rice, Master. Arthur
173 173         1        3      Johnson, Miss. Eleanor Ileen
... ...         ...      ...    ...
692 692         1        3      Karun, Miss. Manca
721 721         1        2      Harper, Miss. Annie Jessie "Nina"
722 722         0        3      Jensen, Mr. Svend Lauritz
732 732         0        3      Hassan, Mr. Houssein G N
747 747         0        3      Abbott, Mr. Rossmore Edward
751 751         1        2      Wells, Miss. Joan
752 752         1        3      Moor, Master. Meier
756 756         1        2      Hamalainen, Master. Viljo
765 765         0        3      Eklund, Mr. Hans Linus
778 778         1        3      Emanuel, Miss. Virginia Ethel
781 781         1        3      Ayoub, Miss. Banoura
782 782         1        1      Dick, Mrs. Albert Adrian (Vera Gillespie)
788 788         0        3      Rice, Master. George Hugh
789 789         1        3      Dean, Master. Bertram Vere
792 792         0        2      Gaskell, Mr. Alfred
803 803         1        1      Carter, Master. William Thornton II
804 804         1        3      Thomas, Master. Assad Alexander
814 814         0        3      Andersson, Miss. Ebba Iris Alfrida
820 820         0        3      Skoog, Master. Karl Thorsten
825 825         0        3      Panula, Master. Urho Abraham
828 828         1        2      Mallet, Master. Andre
831 831         1        3      Yasbeck, Mrs. Antoni (Selini Alexander)
832 832         1        2      Richards, Master. George Sibley
842 842         0        2      Mudd, Mr. Thomas Charles
845 845         0        3      Culumovic, Mr. Jeso
851 851         0        3      Andersson, Master. Sigvard Harald Elias
853 853         0        3      Boulos, Miss. Nourelain
854 854         1        1      Lines, Miss. Mary Conover
870 870         1        3      Johnson, Master. Harold Theodor
876 876         1        3      Najib, Miss. Adele Kiamie "Jane"
    Sex    Age   SibSp Parch Ticket          Fare     Cabin   Embarked
8   male    2.00 3     1     349909          21.0750          S
10  female 14.00 1     0     237736          30.0708          C
11  female  4.00 1     1     PP 9549         16.7000  G6      S
15  female 14.00 0     0     350406           7.8542          S
17  male    2.00 4     1     382652          29.1250          Q
23  female 15.00 0     0     330923           8.0292          Q
25  female  8.00 3     1     349909          21.0750          S
40  female 14.00 1     0     2651            11.2417          C
44  female  3.00 1     2     SC/Paris 2123   41.5792          C
51  male    7.00 4     1     3101295         39.6875          S
59  female  5.00 1     2     C.A. 34651      27.7500          S
60  male   11.00 5     2     CA 2144         46.9000          S
64  male    4.00 3     2     347088          27.9000          S
69  female 17.00 4     2     3101281          7.9250          S
72  female 16.00 5     2     CA 2144         46.9000          S
79  male    0.83 0     2     248738          29.0000          S
85  female 17.00 0     0     SO/C 14885      10.5000          S
87  male   16.00 1     3     W./C. 6608      34.3750          S
112 female 14.50 1     0     2665            14.4542          C
115 female 17.00 0     0     2627            14.4583          C
120 female  2.00 4     2     347082          31.2750          S
126 male   12.00 1     0     2651            11.2417          C
139 male   16.00 0     0     7534             9.2167          S
148 female  9.00 2     2     W./C. 6608      34.3750          S
157 female 16.00 0     0     35851            7.7333          Q
164 male   17.00 0     0     315093           8.6625          S
165 male    1.00 4     1     3101295         39.6875          S
166 male    9.00 0     2     363291          20.5250          S
172 male    4.00 4     1     382652          29.1250          Q
173 female  1.00 1     1     347742          11.1333          S
... ...    ...   ...   ...   ...             ...      ...     ...
692 female  4.00 0     1     349256           13.4167         C
721 female  6.00 0     1     248727           33.0000         S
722 male   17.00 1     0     350048            7.0542         S
732 male   11.00 0     0     2699             18.7875         C
747 male   16.00 1     1     C.A. 2673        20.2500         S
751 female  4.00 1     1     29103            23.0000         S
752 male    6.00 0     1     392096           12.4750 E121    S
756 male    0.67 1     1     250649           14.5000         S
765 male   16.00 0     0     347074            7.7750         S
778 female  5.00 0     0     364516           12.4750         S
781 female 13.00 0     0     2687              7.2292         C
782 female 17.00 1     0     17474            57.0000 B20     S
788 male    8.00 4     1     382652           29.1250         Q
789 male    1.00 1     2     C.A. 2315        20.5750         S
792 male   16.00 0     0     239865           26.0000         S
803 male   11.00 1     2     113760          120.0000 B96 B98 S
804 male    0.42 0     1     2625              8.5167         C
814 female  6.00 4     2     347082           31.2750         S
820 male   10.00 3     2     347088           27.9000         S
825 male    2.00 4     1     3101295          39.6875         S
828 male    1.00 0     2     S.C./PARIS 2079  37.0042         C
831 female 15.00 1     0     2659             14.4542         C
832 male    0.83 1     1     29106            18.7500         S
842 male   16.00 0     0     S.O./P.P. 3      10.5000         S
845 male   17.00 0     0     315090            8.6625         S
851 male    4.00 4     2     347082           31.2750         S
853 female  9.00 1     1     2678             15.2458         C
854 female 16.00 0     1     PC 17592         39.4000 D28     S
870 male    4.00 1     1     347742           11.1333         S
876 female 15.00 0     0     2667              7.2250         C

In [7]:
# 4) Отбор по порту отправления: Найдите всех пассажиров, которые сели на корабль в Саутгемптоне.
subset(titanic, titanic$Embarked == 'S')

    PassengerId Survived Pclass
1    1          0        3
3    3          1        3
4    4          1        1
5    5          0        3
7    7          0        1
8    8          0        3
9    9          1        3
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
18  18          1        2
19  19          0        3
21  21          0        2
22  22          1        2
24  24          1        1
25  25          0        3
26  26          1        3
28  28          0        1
30  30          0        3
34  34          0        2
36  36          0        1
38  38          0        3
39  39          0        3
41  41          0        3
42  42          0        2
46  46          0        3
50  50          0        3
... ...         ...      ...
852 852         0        3
854 854         1        1
855 855         0        2
856 856         1        3
857 857         1        1
858 858         1        1
861 861         0        3
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
877 877         0        3
878 878         0        3
879 879         0        3
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
887 887         0        2
888 888         1        1
889 889         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
28  Fortune, Mr. Charles Alexander                            male   19  3
30  Todoroff, Mr. Lalio                                       male   NA  0
34  Wheadon, Mr. Edward H                                     male   66  0
36  Holverson, Mr. Alexander Oskar                            male   42  1
38  Cann, Mr. Ernest Charles                                  male   21  0
39  Vander Planke, Miss. Augusta Maria                        female 18  2
41  Ahlin, Mrs. Johan (Johanna Persdotter Larsson)            female 40  1
42  Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female 27  1
46  Rogers, Mr. William John                                  male   NA  0
50  Arnold-Franchi, Mrs. Josef (Josefine Franchi)             female 18  1
... ...                                                       ...    ... ...
852 Svensson, Mr. Johan                                       male   74  0
854 Lines, Miss. Mary Conover                                 female 16  0
855 Carter, Mrs. Ernest Courtenay (Lilian Hughes)             female 44  1
856 Aks, Mrs. Sam (Leah Rosen)                                female 18  0
857 Wick, Mrs. George Dennick (Mary Hitchcock)                female 45  1
858 Daly, Mr. Peter Denis                                     male   51  0
861 Hansen, Mr. Claus Peter                                   male   41  2
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
    Parch Ticket           Fare     Cabin       Embarked
1   0     A/5 21171          7.2500             S
3   0     STON/O2. 3101282   7.9250             S
4   0     113803            53.1000 C123        S
5   0     373450             8.0500             S
7   0     17463             51.8625 E46         S
8   1     349909            21.0750             S
9   2     347742            11.1333             S
11  1     PP 9549           16.7000 G6          S
12  0     113783            26.5500 C103        S
13  0     A/5. 2151          8.0500             S
14  5     347082            31.2750             S
15  0     350406             7.8542             S
16  0     248706            16.0000             S
18  0     244373            13.0000             S
19  0     345763            18.0000             S
21  0     239865            26.0000             S
22  0     248698            13.0000 D56         S
24  0     113788            35.5000 A6          S
25  1     349909            21.0750             S
26  5     347077            31.3875             S
28  2     19950            263.0000 C23 C25 C27 S
30  0     349216             7.8958             S
34  0     C.A. 24579        10.5000             S
36  0     113789            52.0000             S
38  0     A./5. 2152         8.0500             S
39  0     345764            18.0000             S
41  0     7546               9.4750             S
42  0     11668             21.0000             S
46  0     S.C./A.4. 23567    8.0500             S
50  0     349237            17.8000             S
... ...   ...              ...      ...         ...
852 0     347060             7.7750             S
854 1     PC 17592          39.4000 D28         S
855 0     244252            26.0000             S
856 1     392091             9.3500             S
857 1     36928            164.8667             S
858 0     113055            26.5500 E17         S
861 0     350026            14.1083             S
862 0     28134             11.5000             S
863 0     17466             25.9292 D17         S
864 2     CA. 2343          69.5500             S
865 0     233866            13.0000             S
866 0     236852            13.0000             S
868 0     PC 17590          50.4958 A24         S
869 0     345777             9.5000             S
870 1     347742            11.1333             S
871 0     349248             7.8958             S
872 1     11751             52.5542 D35         S
873 0     695                5.0000 B51 B53 B55 S
874 0     345765             9.0000             S
877 0     7534               9.8458             S
878 0     349212             7.8958             S
879 0     349217             7.8958             S
881 1     230433            26.0000             S
882 0     349257             7.8958             S
883 0     7552              10.5167             S
884 0     C.A./SOTON 34068  10.5000             S
885 0     SOTON/OQ 392076    7.0500             S
887 0     211536            13.0000             S
888 0     112053            30.0000 B42         S
889 2     W./C. 6607        23.4500             S

In [8]:
# 5) Поиск по фамилии: Найдите всех пассажиров с фамилией, начинающейся на "Smith".
subset(titanic, grepl('Smith', titanic$Name))

    PassengerId Survived Pclass Name                       Sex    Age SibSp
175 175         0        1      Smith, Mr. James Clinch    male   56  0
261 261         0        3      Smith, Mr. Thomas          male   NA  0
285 285         0        1      Smith, Mr. Richard William male   NA  0
347 347         1        2      Smith, Miss. Marion Elsie  female 40  0
    Parch Ticket Fare    Cabin Embarked
175 0     17764  30.6958 A7    C
261 0     384461  7.7500       Q
285 0     113056 26.0000 A19   S
347 0     31418  13.0000       S

In [9]:
# 6) Отбор по стоимости билета: Отберите всех пассажиров, стоимость билета которых была больше 50.
subset(titanic, titanic$Fare > 50)

    PassengerId Survived Pclass
2     2         1        1
4     4         1        1
7     7         0        1
28   28         0        1
32   32         1        1
35   35         0        1
36   36         0        1
53   53         1        1
55   55         0        1
62   62         1        1
63   63         0        1
73   73         0        2
75   75         1        3
89   89         1        1
93   93         0        1
98   98         1        1
103 103         0        1
111 111         0        1
119 119         0        1
121 121         0        2
125 125         0        1
138 138         0        1
140 140         0        1
152 152         1        1
156 156         0        1
160 160         0        3
167 167         1        1
170 170         0        3
181 181         0        3
196 196         1        1
... ...         ...      ...
717 717         1        1
725 725         1        1
731 731         1        1
738 738         1        1
742 742         0        1
743 743         1        1
746 746         0        1
749 749         0        1
755 755         1        2
760 760         1        1
764 764         1        1
766 766         1        1
780 780         1        1
782 782         1        1
790 790         0        1
793 793         0        3
803 803         1        1
810 810         1        1
821 821         1        1
827 827         0        3
830 830         1        1
836 836         1        1
839 839         1        3
847 847         0        3
850 850         1        1
857 857         1        1
864 864         0        3
868 868         0        1
872 872         1        1
880 880         1        1
    Name                                                     Sex    Age SibSp
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)      female 38  1
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)             female 35  1
7   McCarthy, Mr. Timothy J                                  male   54  0
28  Fortune, Mr. Charles Alexander                           male   19  3
32  Spencer, Mrs. William Augustus (Marie Eugenie)           female NA  1
35  Meyer, Mr. Edgar Joseph                                  male   28  1
36  Holverson, Mr. Alexander Oskar                           male   42  1
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)                 female 49  1
55  Ostby, Mr. Engelhart Cornelius                           male   65  0
62  Icard, Miss. Amelie                                      female 38  0
63  Harris, Mr. Henry Birkhardt                              male   45  1
73  Hood, Mr. Ambrose Jr                                     male   21  0
75  Bing, Mr. Lee                                            male   32  0
89  Fortune, Miss. Mabel Helen                               female 23  3
93  Chaffee, Mr. Herbert Fuller                              male   46  1
98  Greenfield, Mr. William Bertram                          male   23  0
103 White, Mr. Richard Frasar                                male   21  0
111 Porter, Mr. Walter Chamberlain                           male   47  0
119 Baxter, Mr. Quigg Edmond                                 male   24  0
121 Hickman, Mr. Stanley George                              male   21  2
125 White, Mr. Percival Wayland                              male   54  0
138 Futrelle, Mr. Jacques Heath                              male   37  1
140 Giglio, Mr. Victor                                       male   24  0
152 Pears, Mrs. Thomas (Edith Wearne)                        female 22  1
156 Williams, Mr. Charles Duane                              male   51  0
160 Sage, Master. Thomas Henry                               male   NA  8
167 Chibnall, Mrs. (Edith Martha Bowerman)                   female NA  0
170 Ling, Mr. Lee                                            male   28  0
181 Sage, Miss. Constance Gladys                             female NA  8
196 Lurette, Miss. Elise                                     female 58  0
... ...                                                      ...    ... ...
717 Endres, Miss. Caroline Louise                            female 38  0
725 Chambers, Mr. Norman Campbell                            male   27  1
731 Allen, Miss. Elisabeth Walton                            female 29  0
738 Lesurer, Mr. Gustave J                                   male   35  0
742 Cavendish, Mr. Tyrell William                            male   36  1
743 Ryerson, Miss. Susan Parker "Suzette"                    female 21  2
746 Crosby, Capt. Edward Gifford                             male   70  1
749 Marvin, Mr. Daniel Warner                                male   19  1
755 Herman, Mrs. Samuel (Jane Laver)                         female 48  1
760 Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards) female 33  0
764 Carter, Mrs. William Ernest (Lucile Polk)                female 36  1
766 Hogeboom, Mrs. John C (Anna Andrews)                     female 51  1
780 Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)    female 43  0
782 Dick, Mrs. Albert Adrian (Vera Gillespie)                female 17  1
790 Guggenheim, Mr. Benjamin                                 male   46  0
793 Sage, Miss. Stella Anna                                  female NA  8
803 Carter, Master. William Thornton II                      male   11  1
810 Chambers, Mrs. Norman Campbell (Bertha Griggs)           female 33  1
821 Hays, Mrs. Charles Melville (Clara Jennings Gregg)       female 52  1
827 Lam, Mr. Len                                             male   NA  0
830 Stone, Mrs. George Nelson (Martha Evelyn)                female 62  0
836 Compton, Miss. Sara Rebecca                              female 39  1
839 Chip, Mr. Chang                                          male   32  0
847 Sage, Mr. Douglas Bullen                                 male   NA  8
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)             female NA  1
857 Wick, Mrs. George Dennick (Mary Hitchcock)               female 45  1
864 Sage, Miss. Dorothy Edith "Dolly"                        female NA  8
868 Roebling, Mr. Washington Augustus II                     male   31  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)         female 47  1
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)            female 56  0
    Parch Ticket       Fare     Cabin           Embarked
2   0     PC 17599      71.2833 C85             C
4   0     113803        53.1000 C123            S
7   0     17463         51.8625 E46             S
28  2     19950        263.0000 C23 C25 C27     S
32  0     PC 17569     146.5208 B78             C
35  0     PC 17604      82.1708                 C
36  0     113789        52.0000                 S
53  0     PC 17572      76.7292 D33             C
55  1     113509        61.9792 B30             C
62  0     113572        80.0000 B28
63  0     36973         83.4750 C83             S
73  0     S.O.C. 14879  73.5000                 S
75  0     1601          56.4958                 S
89  2     19950        263.0000 C23 C25 C27     S
93  0     W.E.P. 5734   61.1750 E31             S
98  1     PC 17759      63.3583 D10 D12         C
103 1     35281         77.2875 D26             S
111 0     110465        52.0000 C110            S
119 1     PC 17558     247.5208 B58 B60         C
121 0     S.O.C. 14879  73.5000                 S
125 1     35281         77.2875 D26             S
138 0     113803        53.1000 C123            S
140 0     PC 17593      79.2000 B86             C
152 0     113776        66.6000 C2              S
156 1     PC 17597      61.3792                 C
160 2     CA. 2343      69.5500                 S
167 1     113505        55.0000 E33             S
170 0     1601          56.4958                 S
181 2     CA. 2343      69.5500                 S
196 0     PC 17569     146.5208 B80             C
... ...   ...          ...      ...             ...
717 0     PC 17757     227.5250 C45             C
725 0     113806        53.1000 E8              S
731 0     24160        211.3375 B5              S
738 0     PC 17755     512.3292 B101            C
742 0     19877         78.8500 C46             S
743 2     PC 17608     262.3750 B57 B59 B63 B66 C
746 1     WE/P 5735     71.0000 B22             S
749 0     113773        53.1000 D30             S
755 2     220845        65.0000                 S
760 0     110152        86.5000 B77             S
764 2     113760       120.0000 B96 B98         S
766 0     13502         77.9583 D11             S
780 1     24160        211.3375 B3              S
782 0     17474         57.0000 B20             S
790 0     PC 17593      79.2000 B82 B84         C
793 2     CA. 2343      69.5500                 S
803 2     113760       120.0000 B96 B98         S
810 0     113806        53.1000 E8              S
821 1     12749         93.5000 B69             S
827 0     1601          56.4958                 S
830 0     113572        80.0000 B28
836 1     PC 17756      83.1583 E49             C
839 0     1601          56.4958                 S
847 2     CA. 2343      69.5500                 S
850 0     17453         89.1042 C92             C
857 1     36928        164.8667                 S
864 2     CA. 2343      69.5500                 S
868 0     PC 17590      50.4958 A24             S
872 1     11751         52.5542 D35             S
880 1     11767         83.1583 C50             C

In [10]:
# 7) Фильтрация по полу: Найдите всех пассажиров женского пола.
subset(titanic, titanic$Sex == 'female')

    PassengerId Survived Pclass
2    2          1        1
3    3          1        3
4    4          1        1
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
15  15          0        3
16  16          1        2
19  19          0        3
20  20          1        3
23  23          1        3
25  25          0        3
26  26          1        3
29  29          1        3
32  32          1        1
33  33          1        3
39  39          0        3
40  40          1        3
41  41          0        3
42  42          0        2
44  44          1        2
45  45          1        3
48  48          1        3
50  50          0        3
53  53          1        1
54  54          1        2
57  57          1        2
59  59          1        2
62  62          1        1
... ...         ...      ...
808 808         0        3
810 810         1        1
814 814         0        3
817 817         0        3
821 821         1        1
824 824         1        3
830 830         1        1
831 831         1        3
836 836         1        1
843 843         1        1
850 850         1        1
853 853         0        3
854 854         1        1
855 855         0        2
856 856         1        3
857 857         1        1
859 859         1        3
863 863         1        1
864 864         0        3
866 866         1        2
867 867         1        2
872 872         1        1
875 875         1        2
876 876         1        3
880 880         1        1
881 881         1        2
883 883         0        3
886 886         0        3
888 888         1        1
889 889         0        3
    Name                                                      Sex    Age SibSp
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
32  Spencer, Mrs. William Augustus (Marie Eugenie)            female NA  1
33  Glynn, Miss. Mary Agatha                                  female NA  0
39  Vander Planke, Miss. Augusta Maria                        female 18  2
40  Nicola-Yarred, Miss. Jamila                               female 14  1
41  Ahlin, Mrs. Johan (Johanna Persdotter Larsson)            female 40  1
42  Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female 27  1
44  Laroche, Miss. Simonne Marie Anne Andree                  female  3  1
45  Devaney, Miss. Margaret Delia                             female 19  0
48  O'Driscoll, Miss. Bridget                                 female NA  0
50  Arnold-Franchi, Mrs. Josef (Josefine Franchi)             female 18  1
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)                  female 49  1
54  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)        female 29  1
57  Rugg, Miss. Emily                                         female 21  0
59  West, Miss. Constance Mirium                              female  5  1
62  Icard, Miss. Amelie                                       female 38  0
... ...                                                       ...    ... ...
808 Pettersson, Miss. Ellen Natalia                           female 18  0
810 Chambers, Mrs. Norman Campbell (Bertha Griggs)            female 33  1
814 Andersson, Miss. Ebba Iris Alfrida                        female  6  4
817 Heininen, Miss. Wendla Maria                              female 23  0
821 Hays, Mrs. Charles Melville (Clara Jennings Gregg)        female 52  1
824 Moor, Mrs. (Beila)                                        female 27  0
830 Stone, Mrs. George Nelson (Martha Evelyn)                 female 62  0
831 Yasbeck, Mrs. Antoni (Selini Alexander)                   female 15  1
836 Compton, Miss. Sara Rebecca                               female 39  1
843 Serepeca, Miss. Augusta                                   female 30  0
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)              female NA  1
853 Boulos, Miss. Nourelain                                   female  9  1
854 Lines, Miss. Mary Conover                                 female 16  0
855 Carter, Mrs. Ernest Courtenay (Lilian Hughes)             female 44  1
856 Aks, Mrs. Sam (Leah Rosen)                                female 18  0
857 Wick, Mrs. George Dennick (Mary Hitchcock)                female 45  1
859 Baclini, Mrs. Solomon (Latifa Qurban)                     female 24  0
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
    Parch Ticket           Fare     Cabin Embarked
2   0     PC 17599          71.2833 C85   C
3   0     STON/O2. 3101282   7.9250       S
4   0     113803            53.1000 C123  S
9   2     347742            11.1333       S
10  0     237736            30.0708       C
11  1     PP 9549           16.7000 G6    S
12  0     113783            26.5500 C103  S
15  0     350406             7.8542       S
16  0     248706            16.0000       S
19  0     345763            18.0000       S
20  0     2649               7.2250       C
23  0     330923             8.0292       Q
25  1     349909            21.0750       S
26  5     347077            31.3875       S
29  0     330959             7.8792       Q
32  0     PC 17569         146.5208 B78   C
33  0     335677             7.7500       Q
39  0     345764            18.0000       S
40  0     2651              11.2417       C
41  0     7546               9.4750       S
42  0     11668             21.0000       S
44  2     SC/Paris 2123     41.5792       C
45  0     330958             7.8792       Q
48  0     14311              7.7500       Q
50  0     349237            17.8000       S
53  0     PC 17572          76.7292 D33   C
54  0     2926              26.0000       S
57  0     C.A. 31026        10.5000       S
59  2     C.A. 34651        27.7500       S
62  0     113572            80.0000 B28
... ...   ...              ...      ...   ...
808 0     347087             7.7750       S
810 0     113806            53.1000 E8    S
814 2     347082            31.2750       S
817 0     STON/O2. 3101290   7.9250       S
821 1     12749             93.5000 B69   S
824 1     392096            12.4750 E121  S
830 0     113572            80.0000 B28
831 0     2659              14.4542       C
836 1     PC 17756          83.1583 E49   C
843 0     113798            31.0000       C
850 0     17453             89.1042 C92   C
853 1     2678              15.2458       C
854 1     PC 17592          39.4000 D28   S
855 0     244252            26.0000       S
856 1     392091             9.3500       S
857 1     36928            164.8667       S
859 3     2666              19.2583       C
863 0     17466             25.9292 D17   S
864 2     CA. 2343          69.5500       S
866 0     236852            13.0000       S
867 0     SC/PARIS 2149     13.8583       C
872 1     11751             52.5542 D35   S
875 0     P/PP 3381         24.0000       C
876 0     2667               7.2250       C
880 1     11767             83.1583 C50   C
881 1     230433            26.0000       S
883 0     7552              10.5167       S
886 5     382652            29.1250       Q
888 0     112053            30.0000 B42   S
889 2     W./C. 6607        23.4500       S

In [11]:
# 8) Отбор пассажиров с несколькими членами семьи на борту: Выберите всех пассажиров, у которых было больше 2 членов семьи на борту.
titanic$families <- titanic$SibSp + titanic$Parch
subset(titanic, titanic$families > 2)

    PassengerId Survived Pclass
8     8         0        3
14   14         0        3
17   17         0        3
25   25         0        3
26   26         1        3
28   28         0        1
44   44         1        2
51   51         0        3
59   59         1        2
60   60         0        3
64   64         0        3
69   69         1        3
72   72         0        3
86   86         1        3
87   87         0        3
89   89         1        1
94   94         0        3
120 120         0        3
148 148         0        3
160 160         0        3
165 165         0        3
168 168         0        3
172 172         0        3
177 177         0        3
181 181         0        3
183 183         0        3
184 184         1        2
202 202         0        3
230 230         0        3
234 234         1        3
... ...         ...      ...
616 616         1        2
619 619         1        2
635 635         0        3
639 639         0        3
643 643         0        3
645 645         1        3
679 679         0        3
684 684         0        3
686 686         0        2
687 687         0        3
727 727         1        2
737 737         0        3
743 743         1        1
755 755         1        2
764 764         1        1
775 775         1        2
784 784         0        3
788 788         0        3
789 789         1        3
793 793         0        3
803 803         1        1
814 814         0        3
820 820         0        3
825 825         0        3
847 847         0        3
851 851         0        3
859 859         1        3
864 864         0        3
886 886         0        3
889 889         0        3
    Name                                                      Sex    Age
8   Palsson, Master. Gosta Leonard                            male    2
14  Andersson, Mr. Anders Johan                               male   39
17  Rice, Master. Eugene                                      male    2
25  Palsson, Miss. Torborg Danira                             female  8
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38
28  Fortune, Mr. Charles Alexander                            male   19
44  Laroche, Miss. Simonne Marie Anne Andree                  female  3
51  Panula, Master. Juha Niilo                                male    7
59  West, Miss. Constance Mirium                              female  5
60  Goodwin, Master. William Frederick                        male   11
64  Skoog, Master. Harald                                     male    4
69  Andersson, Miss. Erna Alexandra                           female 17
72  Goodwin, Miss. Lillian Amy                                female 16
86  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)   female 33
87  Ford, Mr. William Neal                                    male   16
89  Fortune, Miss. Mabel Helen                                female 23
94  Dean, Mr. Bertram Frank                                   male   26
120 Andersson, Miss. Ellis Anna Maria                         female  2
148 Ford, Miss. Robina Maggie "Ruby"                          female  9
160 Sage, Master. Thomas Henry                                male   NA
165 Panula, Master. Eino Viljami                              male    1
168 Skoog, Mrs. William (Anna Bernhardina Karlsson)           female 45
172 Rice, Master. Arthur                                      male    4
177 Lefebre, Master. Henry Forbes                             male   NA
181 Sage, Miss. Constance Gladys                              female NA
183 Asplund, Master. Clarence Gustaf Hugo                     male    9
184 Becker, Master. Richard F                                 male    1
202 Sage, Mr. Frederick                                       male   NA
230 Lefebre, Miss. Mathilde                                   female NA
234 Asplund, Miss. Lillian Gertrud                            female  5
... ...                                                       ...    ...
616 Herman, Miss. Alice                                       female 24.00
619 Becker, Miss. Marion Louise                               female  4.00
635 Skoog, Miss. Mabel                                        female  9.00
639 Panula, Mrs. Juha (Maria Emilia Ojala)                    female 41.00
643 Skoog, Miss. Margit Elizabeth                             female  2.00
645 Baclini, Miss. Eugenie                                    female  0.75
679 Goodwin, Mrs. Frederick (Augusta Tyler)                   female 43.00
684 Goodwin, Mr. Charles Edward                               male   14.00
686 Laroche, Mr. Joseph Philippe Lemercier                    male   25.00
687 Panula, Mr. Jaako Arnold                                  male   14.00
727 Renouf, Mrs. Peter Henry (Lillian Jefferys)               female 30.00
737 Ford, Mrs. Edward (Margaret Ann Watson)                   female 48.00
743 Ryerson, Miss. Susan Parker "Suzette"                     female 21.00
755 Herman, Mrs. Samuel (Jane Laver)                          female 48.00
764 Carter, Mrs. William Ernest (Lucile Polk)                 female 36.00
775 Hocking, Mrs. Elizabeth (Eliza Needs)                     female 54.00
784 Johnston, Mr. Andrew G                                    male      NA
788 Rice, Master. George Hugh                                 male    8.00
789 Dean, Master. Bertram Vere                                male    1.00
793 Sage, Miss. Stella Anna                                   female    NA
803 Carter, Master. William Thornton II                       male   11.00
814 Andersson, Miss. Ebba Iris Alfrida                        female  6.00
820 Skoog, Master. Karl Thorsten                              male   10.00
825 Panula, Master. Urho Abraham                              male    2.00
847 Sage, Mr. Douglas Bullen                                  male      NA
851 Andersson, Master. Sigvard Harald Elias                   male    4.00
859 Baclini, Mrs. Solomon (Latifa Qurban)                     female 24.00
864 Sage, Miss. Dorothy Edith "Dolly"                         female    NA
886 Rice, Mrs. William (Margaret Norton)                      female 39.00
889 Johnston, Miss. Catherine Helen "Carrie"                  female    NA
    SibSp Parch Ticket        Fare     Cabin           Embarked families
8   3     1     349909         21.0750                 S         4
14  1     5     347082         31.2750                 S         6
17  4     1     382652         29.1250                 Q         5
25  3     1     349909         21.0750                 S         4
26  1     5     347077         31.3875                 S         6
28  3     2     19950         263.0000 C23 C25 C27     S         5
44  1     2     SC/Paris 2123  41.5792                 C         3
51  4     1     3101295        39.6875                 S         5
59  1     2     C.A. 34651     27.7500                 S         3
60  5     2     CA 2144        46.9000                 S         7
64  3     2     347088         27.9000                 S         5
69  4     2     3101281         7.9250                 S         6
72  5     2     CA 2144        46.9000                 S         7
86  3     0     3101278        15.8500                 S         3
87  1     3     W./C. 6608     34.3750                 S         4
89  3     2     19950         263.0000 C23 C25 C27     S         5
94  1     2     C.A. 2315      20.5750                 S         3
120 4     2     347082         31.2750                 S         6
148 2     2     W./C. 6608     34.3750                 S         4
160 8     2     CA. 2343       69.5500                 S        10
165 4     1     3101295        39.6875                 S         5
168 1     4     347088         27.9000                 S         5
172 4     1     382652         29.1250                 Q         5
177 3     1     4133           25.4667                 S         4
181 8     2     CA. 2343       69.5500                 S        10
183 4     2     347077         31.3875                 S         6
184 2     1     230136         39.0000 F4              S         3
202 8     2     CA. 2343       69.5500                 S        10
230 3     1     4133           25.4667                 S         4
234 4     2     347077         31.3875                 S         6
... ...   ...   ...           ...      ...             ...      ...
616 1     2     220845         65.0000                 S         3
619 2     1     230136         39.0000 F4              S         3
635 3     2     347088         27.9000                 S         5
639 0     5     3101295        39.6875                 S         5
643 3     2     347088         27.9000                 S         5
645 2     1     2666           19.2583                 C         3
679 1     6     CA 2144        46.9000                 S         7
684 5     2     CA 2144        46.9000                 S         7
686 1     2     SC/Paris 2123  41.5792                 C         3
687 4     1     3101295        39.6875                 S         5
727 3     0     31027          21.0000                 S         3
737 1     3     W./C. 6608     34.3750                 S         4
743 2     2     PC 17608      262.3750 B57 B59 B63 B66 C         4
755 1     2     220845         65.0000                 S         3
764 1     2     113760        120.0000 B96 B98         S         3
775 1     3     29105          23.0000                 S         4
784 1     2     W./C. 6607     23.4500                 S         3
788 4     1     382652         29.1250                 Q         5
789 1     2     C.A. 2315      20.5750                 S         3
793 8     2     CA. 2343       69.5500                 S        10
803 1     2     113760        120.0000 B96 B98         S         3
814 4     2     347082         31.2750                 S         6
820 3     2     347088         27.9000                 S         5
825 4     1     3101295        39.6875                 S         5
847 8     2     CA. 2343       69.5500                 S        10
851 4     2     347082         31.2750                 S         6
859 0     3     2666           19.2583                 C         3
864 8     2     CA. 2343       69.5500                 S        10
886 0     5     382652         29.1250                 Q         5
889 1     2     W./C. 6607     23.4500                 S         3

In [12]:
# 9) Поиск пассажиров с номером каюты: Найдите всех пассажиров, у которых указан номер каюты (Cabin не пустое значение).
subset(titanic, !is.na(titanic$Cabin))

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
... ...         ...      ...
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
... ...                                                       ...    ... ...
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked families
1   0     A/5 21171          7.2500             S        1
2   0     PC 17599          71.2833 C85         C        1
3   0     STON/O2. 3101282   7.9250             S        0
4   0     113803            53.1000 C123        S        1
5   0     373450             8.0500             S        0
6   0     330877             8.4583             Q        0
7   0     17463             51.8625 E46         S        0
8   1     349909            21.0750             S        4
9   2     347742            11.1333             S        2
10  0     237736            30.0708             C        1
11  1     PP 9549           16.7000 G6          S        2
12  0     113783            26.5500 C103        S        0
13  0     A/5. 2151          8.0500             S        0
14  5     347082            31.2750             S        6
15  0     350406             7.8542             S        0
16  0     248706            16.0000             S        0
17  1     382652            29.1250             Q        5
18  0     244373            13.0000             S        0
19  0     345763            18.0000             S        1
20  0     2649               7.2250             C        0
21  0     239865            26.0000             S        0
22  0     248698            13.0000 D56         S        0
23  0     330923             8.0292             Q        0
24  0     113788            35.5000 A6          S        0
25  1     349909            21.0750             S        4
26  5     347077            31.3875             S        6
27  0     2631               7.2250             C        0
28  2     19950            263.0000 C23 C25 C27 S        5
29  0     330959             7.8792             Q        0
30  0     349216             7.8958             S        0
... ...   ...              ...      ...         ...      ...
862 0     28134            11.5000              S         1
863 0     17466            25.9292  D17         S         0
864 2     CA. 2343         69.5500              S        10
865 0     233866           13.0000              S         0
866 0     236852           13.0000              S         0
867 0     SC/PARIS 2149    13.8583              C         1
868 0     PC 17590         50.4958  A24         S         0
869 0     345777            9.5000              S         0
870 1     347742           11.1333              S         2
871 0     349248            7.8958              S         0
872 1     11751            52.5542  D35         S         2
873 0     695               5.0000  B51 B53 B55 S         0
874 0     345765            9.0000              S         0
875 0     P/PP 3381        24.0000              C         1
876 0     2667              7.2250              C         0
877 0     7534              9.8458              S         0
878 0     349212            7.8958              S         0
879 0     349217            7.8958              S         0
880 1     11767            83.1583  C50         C         1
881 1     230433           26.0000              S         1
882 0     349257            7.8958              S         0
883 0     7552             10.5167              S         0
884 0     C.A./SOTON 34068 10.5000              S         0
885 0     SOTON/OQ 392076   7.0500              S         0
886 5     382652           29.1250              Q         5
887 0     211536           13.0000              S         0
888 0     112053           30.0000  B42         S         0
889 2     W./C. 6607       23.4500              S         3
890 0     111369           30.0000  C148        C         0
891 0     370376            7.7500              Q         0

**Задание № 3**

1) Выберите всех выживших пассажиров первого класса: Найдите всех пассажиров, которые ехали в первом классе и выжили.

2) Найдите всех несовершеннолетних, путешествовавших с родителями: Выберите пассажиров младше 18 лет, у которых было хотя бы одно количество родителей на борту.

3) Пассажиры с дорогими билетами и большим возрастом: Найдите всех пассажиров, возраст которых больше 50 лет и стоимость билета которых превышает 100.

4) Женщины, которые выжили и ехали из Квинстауна: Выберите женщин, которые выжили и сели на корабль в Квинстауне.

5) Мужчины третьего класса, путешествовавшие с братьями и сестрами: Найдите всех мужчин, которые ехали в третьем классе и имели хотя бы одного брата или сестру на борту.

6) Пассажиры второго класса с отсутствующим возрастом: Найдите всех пассажиров второго класса, у которых возраст не указан (Age is null).

7) Мужчины старше 30 лет, которые выжили: Выберите всех мужчин старше 30 лет, которые выжили.

8) Дети, ехавшие с обоими родителями: Найдите всех детей младше 12 лет, у которых было как минимум два родителя на борту.

9) Пассажиры старше 60 лет, ехавшие в первом классе, которые не выжили: Выберите всех пассажиров старше 60 лет, которые ехали в первом классе и не выжили.

In [22]:
# 1) Выберите всех выживших пассажиров первого класса: Найдите всех пассажиров, которые ехали в первом классе и выжили.
subset(titanic, titanic$Survived == 1 & titanic$Pclass == 1)

    PassengerId Survived Pclass
2     2         1        1
4     4         1        1
12   12         1        1
24   24         1        1
32   32         1        1
53   53         1        1
56   56         1        1
62   62         1        1
89   89         1        1
98   98         1        1
137 137         1        1
152 152         1        1
167 167         1        1
188 188         1        1
195 195         1        1
196 196         1        1
210 210         1        1
216 216         1        1
219 219         1        1
225 225         1        1
231 231         1        1
249 249         1        1
257 257         1        1
258 258         1        1
259 259         1        1
269 269         1        1
270 270         1        1
276 276         1        1
291 291         1        1
292 292         1        1
... ...         ...      ...
711 711         1        1
713 713         1        1
717 717         1        1
725 725         1        1
731 731         1        1
738 738         1        1
741 741         1        1
743 743         1        1
760 760         1        1
764 764         1        1
766 766         1        1
780 780         1        1
782 782         1        1
797 797         1        1
803 803         1        1
810 810         1        1
821 821         1        1
830 830         1        1
836 836         1        1
840 840         1        1
843 843         1        1
850 850         1        1
854 854         1        1
857 857         1        1
858 858         1        1
863 863         1        1
872 872         1        1
880 880         1        1
888 888         1        1
890 890         1        1
    Name                                                     Sex    Age SibSp
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)      female 38  1
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)             female 35  1
12  Bonnell, Miss. Elizabeth                                 female 58  0
24  Sloper, Mr. William Thompson                             male   28  0
32  Spencer, Mrs. William Augustus (Marie Eugenie)           female NA  1
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)                 female 49  1
56  Woolner, Mr. Hugh                                        male   NA  0
62  Icard, Miss. Amelie                                      female 38  0
89  Fortune, Miss. Mabel Helen                               female 23  3
98  Greenfield, Mr. William Bertram                          male   23  0
137 Newsom, Miss. Helen Monypeny                             female 19  0
152 Pears, Mrs. Thomas (Edith Wearne)                        female 22  1
167 Chibnall, Mrs. (Edith Martha Bowerman)                   female NA  0
188 Romaine, Mr. Charles Hallace ("Mr C Rolmane")            male   45  0
195 Brown, Mrs. James Joseph (Margaret Tobin)                female 44  0
196 Lurette, Miss. Elise                                     female 58  0
210 Blank, Mr. Henry                                         male   40  0
216 Newell, Miss. Madeleine                                  female 31  1
219 Bazzani, Miss. Albina                                    female 32  0
225 Hoyt, Mr. Frederick Maxfield                             male   38  1
231 Harris, Mrs. Henry Birkhardt (Irene Wallach)             female 35  1
249 Beckwith, Mr. Richard Leonard                            male   37  1
257 Thorne, Mrs. Gertrude Maybelle                           female NA  0
258 Cherry, Miss. Gladys                                     female 30  0
259 Ward, Miss. Anna                                         female 35  0
269 Graham, Mrs. William Thompson (Edith Junkins)            female 58  0
270 Bissette, Miss. Amelia                                   female 35  0
276 Andrews, Miss. Kornelia Theodosia                        female 63  1
291 Barber, Miss. Ellen "Nellie"                             female 26  0
292 Bishop, Mrs. Dickinson H (Helen Walton)                  female 19  1
... ...                                                      ...    ... ...
711 Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")         female 24  0
713 Taylor, Mr. Elmer Zebley                                 male   48  1
717 Endres, Miss. Caroline Louise                            female 38  0
725 Chambers, Mr. Norman Campbell                            male   27  1
731 Allen, Miss. Elisabeth Walton                            female 29  0
738 Lesurer, Mr. Gustave J                                   male   35  0
741 Hawksford, Mr. Walter James                              male   NA  0
743 Ryerson, Miss. Susan Parker "Suzette"                    female 21  2
760 Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards) female 33  0
764 Carter, Mrs. William Ernest (Lucile Polk)                female 36  1
766 Hogeboom, Mrs. John C (Anna Andrews)                     female 51  1
780 Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)    female 43  0
782 Dick, Mrs. Albert Adrian (Vera Gillespie)                female 17  1
797 Leader, Dr. Alice (Farnham)                              female 49  0
803 Carter, Master. William Thornton II                      male   11  1
810 Chambers, Mrs. Norman Campbell (Bertha Griggs)           female 33  1
821 Hays, Mrs. Charles Melville (Clara Jennings Gregg)       female 52  1
830 Stone, Mrs. George Nelson (Martha Evelyn)                female 62  0
836 Compton, Miss. Sara Rebecca                              female 39  1
840 Marechal, Mr. Pierre                                     male   NA  0
843 Serepeca, Miss. Augusta                                  female 30  0
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)             female NA  1
854 Lines, Miss. Mary Conover                                female 16  0
857 Wick, Mrs. George Dennick (Mary Hitchcock)               female 45  1
858 Daly, Mr. Peter Denis                                    male   51  0
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)      female 48  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)         female 47  1
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)            female 56  0
888 Graham, Miss. Margaret Edith                             female 19  0
890 Behr, Mr. Karl Howell                                    male   26  0
    Parch Ticket   Fare     Cabin           Embarked families
2   0     PC 17599  71.2833 C85             C        1
4   0     113803    53.1000 C123            S        1
12  0     113783    26.5500 C103            S        0
24  0     113788    35.5000 A6              S        0
32  0     PC 17569 146.5208 B78             C        1
53  0     PC 17572  76.7292 D33             C        1
56  0     19947     35.5000 C52             S        0
62  0     113572    80.0000 B28                      0
89  2     19950    263.0000 C23 C25 C27     S        5
98  1     PC 17759  63.3583 D10 D12         C        1
137 2     11752     26.2833 D47             S        2
152 0     113776    66.6000 C2              S        1
167 1     113505    55.0000 E33             S        1
188 0     111428    26.5500                 S        0
195 0     PC 17610  27.7208 B4              C        0
196 0     PC 17569 146.5208 B80             C        0
210 0     112277    31.0000 A31             C        0
216 0     35273    113.2750 D36             C        1
219 0     11813     76.2917 D15             C        0
225 0     19943     90.0000 C93             S        1
231 0     36973     83.4750 C83             S        1
249 1     11751     52.5542 D35             S        2
257 0     PC 17585  79.2000                 C        0
258 0     110152    86.5000 B77             S        0
259 0     PC 17755 512.3292                 C        0
269 1     PC 17582 153.4625 C125            S        1
270 0     PC 17760 135.6333 C99             S        0
276 0     13502     77.9583 D7              S        1
291 0     19877     78.8500                 S        0
292 0     11967     91.0792 B49             C        1
... ...   ...      ...      ...             ...      ...
711 0     PC 17482  49.5042 C90             C        0
713 0     19996     52.0000 C126            S        1
717 0     PC 17757 227.5250 C45             C        0
725 0     113806    53.1000 E8              S        1
731 0     24160    211.3375 B5              S        0
738 0     PC 17755 512.3292 B101            C        0
741 0     16988     30.0000 D45             S        0
743 2     PC 17608 262.3750 B57 B59 B63 B66 C        4
760 0     110152    86.5000 B77             S        0
764 2     113760   120.0000 B96 B98         S        3
766 0     13502     77.9583 D11             S        1
780 1     24160    211.3375 B3              S        1
782 0     17474     57.0000 B20             S        1
797 0     17465     25.9292 D17             S        0
803 2     113760   120.0000 B96 B98         S        3
810 0     113806    53.1000 E8              S        1
821 1     12749     93.5000 B69             S        2
830 0     113572    80.0000 B28                      0
836 1     PC 17756  83.1583 E49             C        2
840 0     11774     29.7000 C47             C        0
843 0     113798    31.0000                 C        0
850 0     17453     89.1042 C92             C        1
854 1     PC 17592  39.4000 D28             S        1
857 1     36928    164.8667                 S        2
858 0     113055    26.5500 E17             S        0
863 0     17466     25.9292 D17             S        0
872 1     11751     52.5542 D35             S        2
880 1     11767     83.1583 C50             C        1
888 0     112053    30.0000 B42             S        0
890 0     111369    30.0000 C148            C        0

In [23]:
# 2) Найдите всех несовершеннолетних, путешествовавших с родителями: 
# Выберите пассажиров младше 18 лет, у которых было хотя бы одно количество родителей на борту.
subset(titanic, titanic$Age < 18 & titanic$Parch != 0)

    PassengerId Survived Pclass Name
8     8         0        3      Palsson, Master. Gosta Leonard
11   11         1        3      Sandstrom, Miss. Marguerite Rut
17   17         0        3      Rice, Master. Eugene
25   25         0        3      Palsson, Miss. Torborg Danira
44   44         1        2      Laroche, Miss. Simonne Marie Anne Andree
51   51         0        3      Panula, Master. Juha Niilo
59   59         1        2      West, Miss. Constance Mirium
60   60         0        3      Goodwin, Master. William Frederick
64   64         0        3      Skoog, Master. Harald
69   69         1        3      Andersson, Miss. Erna Alexandra
72   72         0        3      Goodwin, Miss. Lillian Amy
79   79         1        2      Caldwell, Master. Alden Gates
87   87         0        3      Ford, Mr. William Neal
120 120         0        3      Andersson, Miss. Ellis Anna Maria
148 148         0        3      Ford, Miss. Robina Maggie "Ruby"
165 165         0        3      Panula, Master. Eino Viljami
166 166         1        3      Goldsmith, Master. Frank John William "Frankie"
172 172         0        3      Rice, Master. Arthur
173 173         1        3      Johnson, Miss. Eleanor Ileen
183 183         0        3      Asplund, Master. Clarence Gustaf Hugo
184 184         1        2      Becker, Master. Richard F
185 185         1        3      Kink-Heilmann, Miss. Luise Gretchen
194 194         1        2      Navratil, Master. Michel M
206 206         0        3      Strom, Miss. Telma Matilda
234 234         1        3      Asplund, Miss. Lillian Gertrud
238 238         1        2      Collyer, Miss. Marjorie "Lottie"
262 262         1        3      Asplund, Master. Edvin Rojj Felix
267 267         0        3      Panula, Mr. Ernesti Arvid
279 279         0        3      Rice, Master. Eric
298 298         0        1      Allison, Miss. Helen Loraine
... ...         ...      ...    ...
542 542         0        3      Andersson, Miss. Ingeborg Constanzia
543 543         0        3      Andersson, Miss. Sigrid Elisabeth
550 550         1        2      Davies, Master. John Morgan Jr
551 551         1        1      Thayer, Mr. John Borland Jr
619 619         1        2      Becker, Miss. Marion Louise
635 635         0        3      Skoog, Miss. Mabel
643 643         0        3      Skoog, Miss. Margit Elizabeth
645 645         1        3      Baclini, Miss. Eugenie
684 684         0        3      Goodwin, Mr. Charles Edward
687 687         0        3      Panula, Mr. Jaako Arnold
690 690         1        1      Madill, Miss. Georgette Alexandra
692 692         1        3      Karun, Miss. Manca
721 721         1        2      Harper, Miss. Annie Jessie "Nina"
747 747         0        3      Abbott, Mr. Rossmore Edward
751 751         1        2      Wells, Miss. Joan
752 752         1        3      Moor, Master. Meier
756 756         1        2      Hamalainen, Master. Viljo
788 788         0        3      Rice, Master. George Hugh
789 789         1        3      Dean, Master. Bertram Vere
803 803         1        1      Carter, Master. William Thornton II
804 804         1        3      Thomas, Master. Assad Alexander
814 814         0        3      Andersson, Miss. Ebba Iris Alfrida
820 820         0        3      Skoog, Master. Karl Thorsten
825 825         0        3      Panula, Master. Urho Abraham
828 828         1        2      Mallet, Master. Andre
832 832         1        2      Richards, Master. George Sibley
851 851         0        3      Andersson, Master. Sigvard Harald Elias
853 853         0        3      Boulos, Miss. Nourelain
854 854         1        1      Lines, Miss. Mary Conover
870 870         1        3      Johnson, Master. Harold Theodor
    Sex    Age   SibSp Parch Ticket          Fare     Cabin   Embarked families
8   male    2.00 3     1     349909           21.0750         S        4
11  female  4.00 1     1     PP 9549          16.7000 G6      S        2
17  male    2.00 4     1     382652           29.1250         Q        5
25  female  8.00 3     1     349909           21.0750         S        4
44  female  3.00 1     2     SC/Paris 2123    41.5792         C        3
51  male    7.00 4     1     3101295          39.6875         S        5
59  female  5.00 1     2     C.A. 34651       27.7500         S        3
60  male   11.00 5     2     CA 2144          46.9000         S        7
64  male    4.00 3     2     347088           27.9000         S        5
69  female 17.00 4     2     3101281           7.9250         S        6
72  female 16.00 5     2     CA 2144          46.9000         S        7
79  male    0.83 0     2     248738           29.0000         S        2
87  male   16.00 1     3     W./C. 6608       34.3750         S        4
120 female  2.00 4     2     347082           31.2750         S        6
148 female  9.00 2     2     W./C. 6608       34.3750         S        4
165 male    1.00 4     1     3101295          39.6875         S        5
166 male    9.00 0     2     363291           20.5250         S        2
172 male    4.00 4     1     382652           29.1250         Q        5
173 female  1.00 1     1     347742           11.1333         S        2
183 male    9.00 4     2     347077           31.3875         S        6
184 male    1.00 2     1     230136           39.0000 F4      S        3
185 female  4.00 0     2     315153           22.0250         S        2
194 male    3.00 1     1     230080           26.0000 F2      S        2
206 female  2.00 0     1     347054           10.4625 G6      S        1
234 female  5.00 4     2     347077           31.3875         S        6
238 female  8.00 0     2     C.A. 31921       26.2500         S        2
262 male    3.00 4     2     347077           31.3875         S        6
267 male   16.00 4     1     3101295          39.6875         S        5
279 male    7.00 4     1     382652           29.1250         Q        5
298 female  2.00 1     2     113781          151.5500 C22 C26 S        3
... ...    ...   ...   ...   ...             ...      ...     ...      ...
542 female  9.00 4     2     347082           31.2750         S        6
543 female 11.00 4     2     347082           31.2750         S        6
550 male    8.00 1     1     C.A. 33112       36.7500         S        2
551 male   17.00 0     2     17421           110.8833 C70     C        2
619 female  4.00 2     1     230136           39.0000 F4      S        3
635 female  9.00 3     2     347088           27.9000         S        5
643 female  2.00 3     2     347088           27.9000         S        5
645 female  0.75 2     1     2666             19.2583         C        3
684 male   14.00 5     2     CA 2144          46.9000         S        7
687 male   14.00 4     1     3101295          39.6875         S        5
690 female 15.00 0     1     24160           211.3375 B5      S        1
692 female  4.00 0     1     349256           13.4167         C        1
721 female  6.00 0     1     248727           33.0000         S        1
747 male   16.00 1     1     C.A. 2673        20.2500         S        2
751 female  4.00 1     1     29103            23.0000         S        2
752 male    6.00 0     1     392096           12.4750 E121    S        1
756 male    0.67 1     1     250649           14.5000         S        2
788 male    8.00 4     1     382652           29.1250         Q        5
789 male    1.00 1     2     C.A. 2315        20.5750         S        3
803 male   11.00 1     2     113760          120.0000 B96 B98 S        3
804 male    0.42 0     1     2625              8.5167         C        1
814 female  6.00 4     2     347082           31.2750         S        6
820 male   10.00 3     2     347088           27.9000         S        5
825 male    2.00 4     1     3101295          39.6875         S        5
828 male    1.00 0     2     S.C./PARIS 2079  37.0042         C        2
832 male    0.83 1     1     29106            18.7500         S        2
851 male    4.00 4     2     347082           31.2750         S        6
853 female  9.00 1     1     2678             15.2458         C        2
854 female 16.00 0     1     PC 17592         39.4000 D28     S        1
870 male    4.00 1     1     347742           11.1333         S        2

In [24]:
# 3) Пассажиры с дорогими билетами и большим возрастом: 
# Найдите всех пассажиров, возраст которых больше 50 лет и стоимость билета которых превышает 100.
subset(titanic, titanic$Age > 50 & titanic$Fare > 100)

    PassengerId Survived Pclass Name
196 196         1        1      Lurette, Miss. Elise
269 269         1        1      Graham, Mrs. William Thompson (Edith Junkins)
439 439         0        1      Fortune, Mr. Mark
660 660         0        1      Newell, Mr. Arthur Webster
    Sex    Age SibSp Parch Ticket   Fare     Cabin       Embarked families
196 female 58  0     0     PC 17569 146.5208 B80         C        0
269 female 58  0     1     PC 17582 153.4625 C125        S        1
439 male   64  1     4     19950    263.0000 C23 C25 C27 S        5
660 male   58  0     2     35273    113.2750 D48         C        2

In [25]:
# 4) Женщины, которые выжили и ехали из Квинстауна: Выберите женщин, которые выжили и сели на корабль в Квинстауне.
subset(titanic, titanic$Sex == 'female' & titanic$Embarked == 'C')

    PassengerId Survived Pclass
2     2         1        1
10   10         1        2
20   20         1        3
32   32         1        1
40   40         1        3
44   44         1        2
53   53         1        1
112 112         0        3
115 115         0        3
129 129         1        3
141 141         0        3
178 178         0        1
195 195         1        1
196 196         1        1
216 216         1        1
219 219         1        1
241 241         0        3
256 256         1        3
257 257         1        1
259 259         1        1
292 292         1        1
300 300         1        1
307 307         1        1
308 308         1        1
310 310         1        1
311 311         1        1
312 312         1        1
320 320         1        1
326 326         1        1
330 330         1        1
... ...         ...      ...
497 497         1        1
514 514         1        1
524 524         1        1
534 534         1        3
538 538         1        1
540 540         1        1
557 557         1        1
579 579         0        3
582 582         1        1
592 592         1        1
609 609         1        2
642 642         1        1
645 645         1        3
692 692         1        3
701 701         1        1
703 703         0        3
711 711         1        1
717 717         1        1
743 743         1        1
781 781         1        3
831 831         1        3
836 836         1        1
843 843         1        1
850 850         1        1
853 853         0        3
859 859         1        3
867 867         1        2
875 875         1        2
876 876         1        3
880 880         1        1
    Name
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)
10  Nasser, Mrs. Nicholas (Adele Achem)
20  Masselmani, Mrs. Fatima
32  Spencer, Mrs. William Augustus (Marie Eugenie)
40  Nicola-Yarred, Miss. Jamila
44  Laroche, Miss. Simonne Marie Anne Andree
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)
112 Zabour, Miss. Hileni
115 Attalah, Miss. Malake
129 Peter, Miss. Anna
141 Boulos, Mrs. Joseph (Sultana)
178 Isham, Miss. Ann Elizabeth
195 Brown, Mrs. James Joseph (Margaret Tobin)
196 Lurette, Miss. Elise
216 Newell, Miss. Madeleine
219 Bazzani, Miss. Albina
241 Zabour, Miss. Thamine
256 Touma, Mrs. Darwis (Hanne Youssef Razi)
257 Thorne, Mrs. Gertrude Maybelle
259 Ward, Miss. Anna
292 Bishop, Mrs. Dickinson H (Helen Walton)
300 Baxter, Mrs. James (Helene DeLaudeniere Chaput)
307 Fleming, Miss. Margaret
308 Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)
310 Francatelli, Miss. Laura Mabel
311 Hays, Miss. Margaret Bechstein
312 Ryerson, Miss. Emily Borie
320 Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)
326 Young, Miss. Marie Grice
330 Hippach, Miss. Jean Gertrude
... ...
497 Eustis, Miss. Elizabeth Mussey
514 Rothschild, Mrs. Martin (Elizabeth L. Barrett)
524 Hippach, Mrs. Louis Albert (Ida Sophia Fischer)
534 Peter, Mrs. Catherine (Catherine Rizk)
538 LeRoy, Miss. Bertha
540 Frolicher, Miss. Hedwig Margaritha
557 Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")
579 Caram, Mrs. Joseph (Maria Elias)
582 Thayer, Mrs. John Borland (Marian Longstreth Morris)
592 Stephenson, Mrs. Walter Bertram (Martha Eustis)
609 Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)
642 Sagesser, Mlle. Emma
645 Baclini, Miss. Eugenie
692 Karun, Miss. Manca
701 Astor, Mrs. John Jacob (Madeleine Talmadge Force)
703 Barbara, Miss. Saiide
711 Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
717 Endres, Miss. Caroline Louise
743 Ryerson, Miss. Susan Parker "Suzette"
781 Ayoub, Miss. Banoura
831 Yasbeck, Mrs. Antoni (Selini Alexander)
836 Compton, Miss. Sara Rebecca
843 Serepeca, Miss. Augusta
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)
853 Boulos, Miss. Nourelain
859 Baclini, Mrs. Solomon (Latifa Qurban)
867 Duran y More, Miss. Asuncion
875 Abelson, Mrs. Samuel (Hannah Wizosky)
876 Najib, Miss. Adele Kiamie "Jane"
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
    Sex    Age   SibSp Parch Ticket        Fare     Cabin           Embarked
2   female 38.0  1     0     PC 17599       71.2833 C85             C
10  female 14.0  1     0     237736         30.0708                 C
20  female   NA  0     0     2649            7.2250                 C
32  female   NA  1     0     PC 17569      146.5208 B78             C
40  female 14.0  1     0     2651           11.2417                 C
44  female  3.0  1     2     SC/Paris 2123  41.5792                 C
53  female 49.0  1     0     PC 17572       76.7292 D33             C
112 female 14.5  1     0     2665           14.4542                 C
115 female 17.0  0     0     2627           14.4583                 C
129 female   NA  1     1     2668           22.3583 F E69           C
141 female   NA  0     2     2678           15.2458                 C
178 female 50.0  0     0     PC 17595       28.7125 C49             C
195 female 44.0  0     0     PC 17610       27.7208 B4              C
196 female 58.0  0     0     PC 17569      146.5208 B80             C
216 female 31.0  1     0     35273         113.2750 D36             C
219 female 32.0  0     0     11813          76.2917 D15             C
241 female   NA  1     0     2665           14.4542                 C
256 female 29.0  0     2     2650           15.2458                 C
257 female   NA  0     0     PC 17585       79.2000                 C
259 female 35.0  0     0     PC 17755      512.3292                 C
292 female 19.0  1     0     11967          91.0792 B49             C
300 female 50.0  0     1     PC 17558      247.5208 B58 B60         C
307 female   NA  0     0     17421         110.8833                 C
308 female 17.0  1     0     PC 17758      108.9000 C65             C
310 female 30.0  0     0     PC 17485       56.9292 E36             C
311 female 24.0  0     0     11767          83.1583 C54             C
312 female 18.0  2     2     PC 17608      262.3750 B57 B59 B63 B66 C
320 female 40.0  1     1     16966         134.5000 E34             C
326 female 36.0  0     0     PC 17760      135.6333 C32             C
330 female 16.0  0     1     111361         57.9792 B18             C
... ...    ...   ...   ...   ...           ...      ...             ...
497 female 54.00 1     0     36947          78.2667 D20             C
514 female 54.00 1     0     PC 17603       59.4000                 C
524 female 44.00 0     1     111361         57.9792 B18             C
534 female    NA 0     2     2668           22.3583                 C
538 female 30.00 0     0     PC 17761      106.4250                 C
540 female 22.00 0     2     13568          49.5000 B39             C
557 female 48.00 1     0     11755          39.6000 A16             C
579 female    NA 1     0     2689           14.4583                 C
582 female 39.00 1     1     17421         110.8833 C68             C
592 female 52.00 1     0     36947          78.2667 D20             C
609 female 22.00 1     2     SC/Paris 2123  41.5792                 C
642 female 24.00 0     0     PC 17477       69.3000 B35             C
645 female  0.75 2     1     2666           19.2583                 C
692 female  4.00 0     1     349256         13.4167                 C
701 female 18.00 1     0     PC 17757      227.5250 C62 C64         C
703 female 18.00 0     1     2691           14.4542                 C
711 female 24.00 0     0     PC 17482       49.5042 C90             C
717 female 38.00 0     0     PC 17757      227.5250 C45             C
743 female 21.00 2     2     PC 17608      262.3750 B57 B59 B63 B66 C
781 female 13.00 0     0     2687            7.2292                 C
831 female 15.00 1     0     2659           14.4542                 C
836 female 39.00 1     1     PC 17756       83.1583 E49             C
843 female 30.00 0     0     113798         31.0000                 C
850 female    NA 1     0     17453          89.1042 C92             C
853 female  9.00 1     1     2678           15.2458                 C
859 female 24.00 0     3     2666           19.2583                 C
867 female 27.00 1     0     SC/PARIS 2149  13.8583                 C
875 female 28.00 1     0     P/PP 3381      24.0000                 C
876 female 15.00 0     0     2667            7.2250                 C
880 female 56.00 0     1     11767          83.1583 C50             C
    families
2   1
10  1
20  0
32  1
40  1
44  3
53  1
112 1
115 0
129 2
141 2
178 0
195 0
196 0
216 1
219 0
241 1
256 2
257 0
259 0
292 1
300 1
307 0
308 1
310 0
311 0
312 4
320 2
326 0
330 1
... ...
497 1
514 1
524 1
534 2
538 0
540 2
557 1
579 1
582 2
592 1
609 3
642 0
645 3
692 1
701 1
703 1
711 0
717 0
743 4
781 0
831 1
836 2
843 0
850 1
853 2
859 3
867 1
875 1
876 0
880 1

In [26]:
# 5) Мужчины третьего класса, путешествовавшие с братьями и сестрами: 
# Найдите всех мужчин, которые ехали в третьем классе и имели хотя бы одного брата или сестру на борту.
subset(titanic, titanic$Sex == 'male' & titanic$Pclass == 3 & SibSp != 0)

    PassengerId Survived Pclass
1     1         0        3
8     8         0        3
14   14         0        3
17   17         0        3
47   47         0        3
49   49         0        3
51   51         0        3
60   60         0        3
64   64         0        3
66   66         1        3
70   70         0        3
74   74         0        3
87   87         0        3
94   94         0        3
105 105         0        3
126 126         1        3
160 160         0        3
165 165         0        3
172 172         0        3
176 176         0        3
177 177         0        3
183 183         0        3
189 189         0        3
202 202         0        3
207 207         0        3
215 215         0        3
254 254         0        3
262 262         1        3
267 267         0        3
268 268         1        3
... ...         ...      ...
481 481         0        3
490 490         1        3
491 491         0        3
533 533         0        3
549 549         0        3
566 566         0        3
596 596         0        3
606 606         0        3
617 617         0        3
621 621         0        3
623 623         1        3
640 640         0        3
665 665         1        3
684 684         0        3
687 687         0        3
705 705         0        3
710 710         1        3
722 722         0        3
744 744         0        3
747 747         0        3
769 769         0        3
784 784         0        3
788 788         0        3
789 789         1        3
820 820         0        3
825 825         0        3
847 847         0        3
851 851         0        3
861 861         0        3
870 870         1        3
    Name                                              Sex  Age SibSp Parch
1   Braund, Mr. Owen Harris                           male 22  1     0
8   Palsson, Master. Gosta Leonard                    male  2  3     1
14  Andersson, Mr. Anders Johan                       male 39  1     5
17  Rice, Master. Eugene                              male  2  4     1
47  Lennon, Mr. Denis                                 male NA  1     0
49  Samaan, Mr. Youssef                               male NA  2     0
51  Panula, Master. Juha Niilo                        male  7  4     1
60  Goodwin, Master. William Frederick                male 11  5     2
64  Skoog, Master. Harald                             male  4  3     2
66  Moubarek, Master. Gerios                          male NA  1     1
70  Kink, Mr. Vincenz                                 male 26  2     0
74  Chronopoulos, Mr. Apostolos                       male 26  1     0
87  Ford, Mr. William Neal                            male 16  1     3
94  Dean, Mr. Bertram Frank                           male 26  1     2
105 Gustafsson, Mr. Anders Vilhelm                    male 37  2     0
126 Nicola-Yarred, Master. Elias                      male 12  1     0
160 Sage, Master. Thomas Henry                        male NA  8     2
165 Panula, Master. Eino Viljami                      male  1  4     1
172 Rice, Master. Arthur                              male  4  4     1
176 Klasen, Mr. Klas Albin                            male 18  1     1
177 Lefebre, Master. Henry Forbes                     male NA  3     1
183 Asplund, Master. Clarence Gustaf Hugo             male  9  4     2
189 Bourke, Mr. John                                  male 40  1     1
202 Sage, Mr. Frederick                               male NA  8     2
207 Backstrom, Mr. Karl Alfred                        male 32  1     0
215 Kiernan, Mr. Philip                               male NA  1     0
254 Lobb, Mr. William Arthur                          male 30  1     0
262 Asplund, Master. Edvin Rojj Felix                 male  3  4     2
267 Panula, Mr. Ernesti Arvid                         male 16  4     1
268 Persson, Mr. Ernst Ulrik                          male 25  1     0
... ...                                               ...  ... ...   ...
481 Goodwin, Master. Harold Victor                    male  9  5     2
490 Coutts, Master. Eden Leslie "Neville"             male  9  1     1
491 Hagland, Mr. Konrad Mathias Reiersen              male NA  1     0
533 Elias, Mr. Joseph Jr                              male 17  1     1
549 Goldsmith, Mr. Frank John                         male 33  1     1
566 Davies, Mr. Alfred J                              male 24  2     0
596 Van Impe, Mr. Jean Baptiste                       male 36  1     1
606 Lindell, Mr. Edvard Bengtsson                     male 36  1     0
617 Danbom, Mr. Ernst Gilbert                         male 34  1     1
621 Yasbeck, Mr. Antoni                               male 27  1     0
623 Nakid, Mr. Sahid                                  male 20  1     1
640 Thorneycroft, Mr. Percival                        male NA  1     0
665 Lindqvist, Mr. Eino William                       male 20  1     0
684 Goodwin, Mr. Charles Edward                       male 14  5     2
687 Panula, Mr. Jaako Arnold                          male 14  4     1
705 Hansen, Mr. Henrik Juul                           male 26  1     0
710 Moubarek, Master. Halim Gonios ("William George") male NA  1     1
722 Jensen, Mr. Svend Lauritz                         male 17  1     0
744 McNamee, Mr. Neal                                 male 24  1     0
747 Abbott, Mr. Rossmore Edward                       male 16  1     1
769 Moran, Mr. Daniel J                               male NA  1     0
784 Johnston, Mr. Andrew G                            male NA  1     2
788 Rice, Master. George Hugh                         male  8  4     1
789 Dean, Master. Bertram Vere                        male  1  1     2
820 Skoog, Master. Karl Thorsten                      male 10  3     2
825 Panula, Master. Urho Abraham                      male  2  4     1
847 Sage, Mr. Douglas Bullen                          male NA  8     2
851 Andersson, Master. Sigvard Harald Elias           male  4  4     2
861 Hansen, Mr. Claus Peter                           male 41  2     0
870 Johnson, Master. Harold Theodor                   male  4  1     1
    Ticket            Fare    Cabin Embarked families
1   A/5 21171          7.2500       S         1
8   349909            21.0750       S         4
14  347082            31.2750       S         6
17  382652            29.1250       Q         5
47  370371            15.5000       Q         1
49  2662              21.6792       C         2
51  3101295           39.6875       S         5
60  CA 2144           46.9000       S         7
64  347088            27.9000       S         5
66  2661              15.2458       C         2
70  315151             8.6625       S         2
74  2680              14.4542       C         1
87  W./C. 6608        34.3750       S         4
94  C.A. 2315         20.5750       S         3
105 3101276            7.9250       S         2
126 2651              11.2417       C         1
160 CA. 2343          69.5500       S        10
165 3101295           39.6875       S         5
172 382652            29.1250       Q         5
176 350404             7.8542       S         2
177 4133              25.4667       S         4
183 347077            31.3875       S         6
189 364849            15.5000       Q         2
202 CA. 2343          69.5500       S        10
207 3101278           15.8500       S         1
215 367229             7.7500       Q         1
254 A/5. 3336         16.1000       S         1
262 347077            31.3875       S         6
267 3101295           39.6875       S         5
268 347083             7.7750       S         1
... ...               ...     ...   ...      ...
481 CA 2144           46.9000       S         7
490 C.A. 37671        15.9000       S         2
491 65304             19.9667       S         1
533 2690               7.2292       C         2
549 363291            20.5250       S         2
566 A/4 48871         24.1500       S         2
596 345773            24.1500       S         2
606 349910            15.5500       S         1
617 347080            14.4000       S         2
621 2659              14.4542       C         1
623 2653              15.7417       C         2
640 376564            16.1000       S         1
665 STON/O 2. 3101285  7.9250       S         1
684 CA 2144           46.9000       S         7
687 3101295           39.6875       S         5
705 350025             7.8542       S         1
710 2661              15.2458       C         2
722 350048             7.0542       S         1
744 376566            16.1000       S         1
747 C.A. 2673         20.2500       S         2
769 371110            24.1500       Q         1
784 W./C. 6607        23.4500       S         3
788 382652            29.1250       Q         5
789 C.A. 2315         20.5750       S         3
820 347088            27.9000       S         5
825 3101295           39.6875       S         5
847 CA. 2343          69.5500       S        10
851 347082            31.2750       S         6
861 350026            14.1083       S         2
870 347742            11.1333       S         2

In [28]:
# 6) Пассажиры второго класса с отсутствующим возрастом: Найдите всех пассажиров второго класса, у которых возраст не указан (Age is null).
subset(titanic, is.na(titanic$Age) & titanic$Pclass == 2)

    PassengerId Survived Pclass Name                             Sex    Age
18   18         1        2      Williams, Mr. Charles Eugene     male   NA
182 182         0        2      Pernot, Mr. Rene                 male   NA
278 278         0        2      Parkes, Mr. Francis "Frank"      male   NA
304 304         1        2      Keane, Miss. Nora A              female NA
414 414         0        2      Cunningham, Mr. Alfred Fleming   male   NA
467 467         0        2      Campbell, Mr. William            male   NA
482 482         0        2      Frost, Mr. Anthony Wood "Archie" male   NA
548 548         1        2      Padro y Manent, Mr. Julian       male   NA
597 597         1        2      Leitch, Miss. Jessie Wills       female NA
675 675         0        2      Watson, Mr. Ennis Hastings       male   NA
733 733         0        2      Knight, Mr. Robert J             male   NA
    SibSp Parch Ticket        Fare    Cabin Embarked families
18  0     0     244373        13.0000       S        0
182 0     0     SC/PARIS 2131 15.0500       C        0
278 0     0     239853         0.0000       S        0
304 0     0     226593        12.3500 E101  Q        0
414 0     0     239853         0.0000       S        0
467 0     0     239853         0.0000       S        0
482 0     0     239854         0.0000       S        0
548 0     0     SC/PARIS 2146 13.8625       C        0
597 0     0     248727        33.0000       S        0
675 0     0     239856         0.0000       S        0
733 0     0     239855         0.0000       S        0

In [29]:
# 7) Мужчины старше 30 лет, которые выжили: Выберите всех мужчин старше 30 лет, которые выжили.
subset(titanic, titanic$Sex > 30 & titanic$Survived == 1)

    PassengerId Survived Pclass
2    2          1        1
3    3          1        3
4    4          1        1
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
16  16          1        2
18  18          1        2
20  20          1        3
22  22          1        2
23  23          1        3
24  24          1        1
26  26          1        3
29  29          1        3
32  32          1        1
33  33          1        3
37  37          1        3
40  40          1        3
44  44          1        2
45  45          1        3
48  48          1        3
53  53          1        1
54  54          1        2
56  56          1        1
57  57          1        2
59  59          1        2
62  62          1        1
66  66          1        3
67  67          1        2
... ...         ...      ...
810 810         1        1
821 821         1        1
822 822         1        3
824 824         1        3
828 828         1        2
829 829         1        3
830 830         1        1
831 831         1        3
832 832         1        2
836 836         1        1
839 839         1        3
840 840         1        1
843 843         1        1
850 850         1        1
854 854         1        1
856 856         1        3
857 857         1        1
858 858         1        1
859 859         1        3
863 863         1        1
866 866         1        2
867 867         1        2
870 870         1        3
872 872         1        1
875 875         1        2
876 876         1        3
880 880         1        1
881 881         1        2
888 888         1        1
890 890         1        1
    Name                                                      Sex    Age
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38
3   Heikkinen, Miss. Laina                                    female 26
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14
11  Sandstrom, Miss. Marguerite Rut                           female  4
12  Bonnell, Miss. Elizabeth                                  female 58
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55
18  Williams, Mr. Charles Eugene                              male   NA
20  Masselmani, Mrs. Fatima                                   female NA
22  Beesley, Mr. Lawrence                                     male   34
23  McGowan, Miss. Anna "Annie"                               female 15
24  Sloper, Mr. William Thompson                              male   28
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA
32  Spencer, Mrs. William Augustus (Marie Eugenie)            female NA
33  Glynn, Miss. Mary Agatha                                  female NA
37  Mamee, Mr. Hanna                                          male   NA
40  Nicola-Yarred, Miss. Jamila                               female 14
44  Laroche, Miss. Simonne Marie Anne Andree                  female  3
45  Devaney, Miss. Margaret Delia                             female 19
48  O'Driscoll, Miss. Bridget                                 female NA
53  Harper, Mrs. Henry Sleeper (Myna Haxtun)                  female 49
54  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)        female 29
56  Woolner, Mr. Hugh                                         male   NA
57  Rugg, Miss. Emily                                         female 21
59  West, Miss. Constance Mirium                              female  5
62  Icard, Miss. Amelie                                       female 38
66  Moubarek, Master. Gerios                                  male   NA
67  Nye, Mrs. (Elizabeth Ramell)                              female 29
... ...                                                       ...    ...
810 Chambers, Mrs. Norman Campbell (Bertha Griggs)            female 33.00
821 Hays, Mrs. Charles Melville (Clara Jennings Gregg)        female 52.00
822 Lulic, Mr. Nikola                                         male   27.00
824 Moor, Mrs. (Beila)                                        female 27.00
828 Mallet, Master. Andre                                     male    1.00
829 McCormack, Mr. Thomas Joseph                              male      NA
830 Stone, Mrs. George Nelson (Martha Evelyn)                 female 62.00
831 Yasbeck, Mrs. Antoni (Selini Alexander)                   female 15.00
832 Richards, Master. George Sibley                           male    0.83
836 Compton, Miss. Sara Rebecca                               female 39.00
839 Chip, Mr. Chang                                           male   32.00
840 Marechal, Mr. Pierre                                      male      NA
843 Serepeca, Miss. Augusta                                   female 30.00
850 Goldenberg, Mrs. Samuel L (Edwiga Grabowska)              female    NA
854 Lines, Miss. Mary Conover                                 female 16.00
856 Aks, Mrs. Sam (Leah Rosen)                                female 18.00
857 Wick, Mrs. George Dennick (Mary Hitchcock)                female 45.00
858 Daly, Mr. Peter Denis                                     male   51.00
859 Baclini, Mrs. Solomon (Latifa Qurban)                     female 24.00
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48.00
866 Bystrom, Mrs. (Karolina)                                  female 42.00
867 Duran y More, Miss. Asuncion                              female 27.00
870 Johnson, Master. Harold Theodor                           male    4.00
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47.00
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28.00
876 Najib, Miss. Adele Kiamie "Jane"                          female 15.00
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56.00
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25.00
888 Graham, Miss. Margaret Edith                              female 19.00
890 Behr, Mr. Karl Howell                                     male   26.00
    SibSp Parch Ticket           Fare     Cabin Embarked families
2   1     0     PC 17599          71.2833 C85   C        1
3   0     0     STON/O2. 3101282   7.9250       S        0
4   1     0     113803            53.1000 C123  S        1
9   0     2     347742            11.1333       S        2
10  1     0     237736            30.0708       C        1
11  1     1     PP 9549           16.7000 G6    S        2
12  0     0     113783            26.5500 C103  S        0
16  0     0     248706            16.0000       S        0
18  0     0     244373            13.0000       S        0
20  0     0     2649               7.2250       C        0
22  0     0     248698            13.0000 D56   S        0
23  0     0     330923             8.0292       Q        0
24  0     0     113788            35.5000 A6    S        0
26  1     5     347077            31.3875       S        6
29  0     0     330959             7.8792       Q        0
32  1     0     PC 17569         146.5208 B78   C        1
33  0     0     335677             7.7500       Q        0
37  0     0     2677               7.2292       C        0
40  1     0     2651              11.2417       C        1
44  1     2     SC/Paris 2123     41.5792       C        3
45  0     0     330958             7.8792       Q        0
48  0     0     14311              7.7500       Q        0
53  1     0     PC 17572          76.7292 D33   C        1
54  1     0     2926              26.0000       S        1
56  0     0     19947             35.5000 C52   S        0
57  0     0     C.A. 31026        10.5000       S        0
59  1     2     C.A. 34651        27.7500       S        3
62  0     0     113572            80.0000 B28            0
66  1     1     2661              15.2458       C        2
67  0     0     C.A. 29395        10.5000 F33   S        0
... ...   ...   ...              ...      ...   ...      ...
810 1     0     113806            53.1000 E8    S        1
821 1     1     12749             93.5000 B69   S        2
822 0     0     315098             8.6625       S        0
824 0     1     392096            12.4750 E121  S        1
828 0     2     S.C./PARIS 2079   37.0042       C        2
829 0     0     367228             7.7500       Q        0
830 0     0     113572            80.0000 B28            0
831 1     0     2659              14.4542       C        1
832 1     1     29106             18.7500       S        2
836 1     1     PC 17756          83.1583 E49   C        2
839 0     0     1601              56.4958       S        0
840 0     0     11774             29.7000 C47   C        0
843 0     0     113798            31.0000       C        0
850 1     0     17453             89.1042 C92   C        1
854 0     1     PC 17592          39.4000 D28   S        1
856 0     1     392091             9.3500       S        1
857 1     1     36928            164.8667       S        2
858 0     0     113055            26.5500 E17   S        0
859 0     3     2666              19.2583       C        3
863 0     0     17466             25.9292 D17   S        0
866 0     0     236852            13.0000       S        0
867 1     0     SC/PARIS 2149     13.8583       C        1
870 1     1     347742            11.1333       S        2
872 1     1     11751             52.5542 D35   S        2
875 1     0     P/PP 3381         24.0000       C        1
876 0     0     2667               7.2250       C        0
880 0     1     11767             83.1583 C50   C        1
881 0     1     230433            26.0000       S        1
888 0     0     112053            30.0000 B42   S        0
890 0     0     111369            30.0000 C148  C        0

In [30]:
# 8) Дети, ехавшие с обоими родителями: Найдите всех детей младше 12 лет, 
# у которых было как минимум два родителя на борту.
subset(titanic, titanic$Age <12 & titanic$Parch == 2)

    PassengerId Survived Pclass Name
44   44         1        2      Laroche, Miss. Simonne Marie Anne Andree
59   59         1        2      West, Miss. Constance Mirium
60   60         0        3      Goodwin, Master. William Frederick
64   64         0        3      Skoog, Master. Harald
79   79         1        2      Caldwell, Master. Alden Gates
120 120         0        3      Andersson, Miss. Ellis Anna Maria
148 148         0        3      Ford, Miss. Robina Maggie "Ruby"
166 166         1        3      Goldsmith, Master. Frank John William "Frankie"
183 183         0        3      Asplund, Master. Clarence Gustaf Hugo
185 185         1        3      Kink-Heilmann, Miss. Luise Gretchen
234 234         1        3      Asplund, Miss. Lillian Gertrud
238 238         1        2      Collyer, Miss. Marjorie "Lottie"
262 262         1        3      Asplund, Master. Edvin Rojj Felix
298 298         0        1      Allison, Miss. Helen Loraine
306 306         1        1      Allison, Master. Hudson Trevor
382 382         1        3      Nakid, Miss. Maria ("Mary")
387 387         0        3      Goodwin, Master. Sidney Leonard
420 420         0        3      Van Impe, Miss. Catharina
446 446         1        1      Dodge, Master. Washington
481 481         0        3      Goodwin, Master. Harold Victor
536 536         1        2      Hart, Miss. Eva Miriam
542 542         0        3      Andersson, Miss. Ingeborg Constanzia
543 543         0        3      Andersson, Miss. Sigrid Elisabeth
635 635         0        3      Skoog, Miss. Mabel
643 643         0        3      Skoog, Miss. Margit Elizabeth
789 789         1        3      Dean, Master. Bertram Vere
803 803         1        1      Carter, Master. William Thornton II
814 814         0        3      Andersson, Miss. Ebba Iris Alfrida
820 820         0        3      Skoog, Master. Karl Thorsten
828 828         1        2      Mallet, Master. Andre
851 851         0        3      Andersson, Master. Sigvard Harald Elias
    Sex    Age   SibSp Parch Ticket          Fare     Cabin   Embarked families
44  female  3.00 1     2     SC/Paris 2123    41.5792         C        3
59  female  5.00 1     2     C.A. 34651       27.7500         S        3
60  male   11.00 5     2     CA 2144          46.9000         S        7
64  male    4.00 3     2     347088           27.9000         S        5
79  male    0.83 0     2     248738           29.0000         S        2
120 female  2.00 4     2     347082           31.2750         S        6
148 female  9.00 2     2     W./C. 6608       34.3750         S        4
166 male    9.00 0     2     363291           20.5250         S        2
183 male    9.00 4     2     347077           31.3875         S        6
185 female  4.00 0     2     315153           22.0250         S        2
234 female  5.00 4     2     347077           31.3875         S        6
238 female  8.00 0     2     C.A. 31921       26.2500         S        2
262 male    3.00 4     2     347077           31.3875         S        6
298 female  2.00 1     2     113781          151.5500 C22 C26 S        3
306 male    0.92 1     2     113781          151.5500 C22 C26 S        3
382 female  1.00 0     2     2653             15.7417         C        2
387 male    1.00 5     2     CA 2144          46.9000         S        7
420 female 10.00 0     2     345773           24.1500         S        2
446 male    4.00 0     2     33638            81.8583 A34     S        2
481 male    9.00 5     2     CA 2144          46.9000         S        7
536 female  7.00 0     2     F.C.C. 13529     26.2500         S        2
542 female  9.00 4     2     347082           31.2750         S        6
543 female 11.00 4     2     347082           31.2750         S        6
635 female  9.00 3     2     347088           27.9000         S        5
643 female  2.00 3     2     347088           27.9000         S        5
789 male    1.00 1     2     C.A. 2315        20.5750         S        3
803 male   11.00 1     2     113760          120.0000 B96 B98 S        3
814 female  6.00 4     2     347082           31.2750         S        6
820 male   10.00 3     2     347088           27.9000         S        5
828 male    1.00 0     2     S.C./PARIS 2079  37.0042         C        2
851 male    4.00 4     2     347082           31.2750         S        6

In [31]:
# 9) Пассажиры старше 60 лет, ехавшие в первом классе, которые не выжили: 
# Выберите всех пассажиров старше 60 лет, которые ехали в первом классе и не выжили.
subset(titanic, titanic$Age > 60 & titanic$Pclass == 1 & titanic$Survived == 0)

    PassengerId Survived Pclass Name                           Sex  Age SibSp
55   55         0        1      Ostby, Mr. Engelhart Cornelius male 65  0
97   97         0        1      Goldschmidt, Mr. George B      male 71  0
171 171         0        1      Van der hoef, Mr. Wyckoff      male 61  0
253 253         0        1      Stead, Mr. William Thomas      male 62  0
439 439         0        1      Fortune, Mr. Mark              male 64  1
457 457         0        1      Millet, Mr. Francis Davis      male 65  0
494 494         0        1      Artagaveytia, Mr. Ramon        male 71  0
546 546         0        1      Nicholson, Mr. Arthur Ernest   male 64  0
556 556         0        1      Wright, Mr. George             male 62  0
626 626         0        1      Sutton, Mr. Frederick          male 61  0
746 746         0        1      Crosby, Capt. Edward Gifford   male 70  1
    Parch Ticket    Fare     Cabin       Embarked families
55  1     113509     61.9792 B30         C        1
97  0     PC 17754   34.6542 A5          C        0
171 0     111240     33.5000 B19         S        0
253 0     113514     26.5500 C87         S        0
439 4     19950     263.0000 C23 C25 C27 S        5
457 0     13509      26.5500 E38         S        0
494 0     PC 17609   49.5042             C        0
546 0     693        26.0000             S        0
556 0     113807     26.5500             S        0
626 0     36963      32.3208 D50         S        0
746 1     WE/P 5735  71.0000 B22         S        2